### ISSUE TITLE
Error while submitting shop to forums: Duplicate submission protection enabled. You may have submitted this form already. If you haven't then please submit it again. 

### ISSUE THREAD

**Issue by fromangee** [xyzz/acquisition#100]
i keep betting this and nomatter if i reinstall or restart i keep getting it... does anyone else get this problem? and if so does anyone know how to fix it?

**Comment by Tvangeste** [comment]
Maybe it is just a warning and has no negative consequences... At least I see that my shop is being updated with no problems.

**Comment by M4A1Silenced** [comment]
I am getting this issue too
"ERROR 2015-07-29T17:11:57.863 Error while submitting shop to forums: item tag missing 'post' attribute</li><li>item tag missing 'index' attribute"

**Comment by xyzz** [comment]
Can you check which item causes the issue?

**Comment by xyzz** [comment]
Fixed in 0.3.
