### ISSUE TITLE
problems posting to my shop thread

### ISSUE THREAD

**Issue by facelessman122** [xyzz/acquisition#101]
ive set the program up, entered shot thread number, sorted tabs etc and nothing works.

i keep getting this error

ERROR 2015-07-21T15:53:58.385 Error while submitting shop to forums: item tag missing 'post' attribute</li><li>item tag missing 'index' attribute 

Any ideas?

**Comment by M4A1Silenced** [comment]
Having the same problem please solve it fast, I don't like using procurement

**Comment by facelessman122** [comment]
I sorted it out. Unsurprisingly it was my fault. I had  accidently changed the shop template box in the options, it needs to be [item] .

Working great!
