### ISSUE TITLE
Suggestion: Ability to select and price multiple items at once

### ISSUE THREAD

**Issue by HeavensRejected** [xyzz/acquisition#102]
I'm not sure how big the demand for such a feature is and how hard it would be to implement but I'd really like to be able to select and price multiple items at once.

The usual modifier for selecting items in a list is Ctrl.
So I'd be able to Ctrl+click for example 6 items, select the price and it applies to all selected items.

I realize that there's an option to create a seperate stash tab for a specific price but some of us don't have enough stash tabs to do this and it would be unrealistic to create a seperate stash tab for every single price you'd like to do.

**Comment by xyzz** [comment]
dupe #40
