### ISSUE TITLE
Failed to find item

### ISSUE THREAD

**Issue by YodaForcedMe** [xyzz/acquisition#105]
So I have been messing with this for ~ hr watched a few videos and figured I would try setting up a shop. The issue I am running into frequently is Failed to find item. Did you specify the correct location and x y. I have googled the issue and tried a few fixes and so far nothing has worked. The items have been in the same location in my stash for the last 40 minutes and the error is still happening.

**Comment by xyzz** [comment]
Should be fixed in 0.3a, if this still happens please reopen the issue or open another one.
