### ISSUE TITLE
Quality of life improvements

### ISSUE THREAD

**Issue by Nzash** [xyzz/acquisition#106]
Really liking Acquisition so far, very fast, light-weight and has just what I need. 

However I noticed that upon expanding/collapsing stash tabs it keeps resetting the "width/size" of the fields such as name/quality etc. 

Especially the name field gets shortened a lot so items read like this: "Beast B..." or "Vaal Sp..." 

There also seems to be no way to close an extra tab you opened by clicking on the + 

Just some small QoL suggestions

**Comment by Novynn** [comment]
> There also seems to be no way to close an extra tab you opened by clicking on the +

If you middle click with your mouse it should close.

**Comment by xyzz** [comment]
Fixed by 7aee89cf8ae28da25b9ae8a825f51a81c097fffb
