### ISSUE TITLE
I got this error after opening Acquisition

### ISSUE THREAD

**Issue by AntiMatterDotA** [xyzz/acquisition#113]
Tried to open acquisition today and my anti-virus picked it up as executing a trojan and removed it. Not too sure why as all was working fine before. Google search hasn't given me much detail. Any suggestions on how this was caused or why?
The below is copied and pasted from the anti-virus removal tool, don't know if that will help you. Need anything else then please ask. Don't want to stop using the program because of this :(
------------------------------------------------------------------------------------
Filename: acquisition.exe
Threat name: SONAR.Heuristic.120Full Path: Not Available
____________________________
____________________________
On computers as of 
23/07/2015 at 14:02:00
Last Used 
23/07/2015 at 14:02:00
Startup Item 
No
Launched 
Yes
SONAR Protection monitors for suspicious program activity on your computer.
____________________________
acquisition.exe Threat name: SONAR.Heuristic.120
Locate
Few Users
Hundreds of users in the Norton Community have used this file.
New
This file was released 22 days ago.
High
This file risk is high.
____________________________
Source: External Media
Source File:
acquisition.exe
____________________________
File Actions
File: d:\program files (x86)\acquisition\ acquisition.exe Threat Removed
____________________________
Network Actions
Event: Network activity (Performed by d:\program files (x86)\acquisition\acquisition.exe, PID:5764) No action taken
____________________________
System Settings Actions
Event: Process start (Performed by d:\program files (x86)\acquisition\acquisition.exe, PID:5764) No action taken
Event: Process start: d:\program files (x86)\acquisition\ acquisition.exe, PID:5764 (Performed by d:\program files (x86)\acquisition\acquisition.exe, PID:5764) No action taken
____________________________
File Thumbprint - SHA:
Not available
File Thumbprint - MD5:
Not available

**Comment by xyzz** [comment]
merging into #148
