### ISSUE TITLE
 Missing: Increased Attack Speed - Mod

### ISSUE THREAD

**Issue by EdenDorf** [xyzz/acquisition#115]
Increased Attack Speed - Mod
I cant search for this mod in my stash... And i need it :D 
Also i diddne found Increased Evasion - Mod

Maybe you can make a search for mods where i could define by my self what im looking for? Some typefeild, you know?

**Comment by xyzz** [comment]
I've added the "increased attack speed" mod. Why is there a need for "increased evasion" mod? You already can search by evasion value.

As of now there are no plans to implement user defined mods.

**Comment by xyzz** [comment]
No reply in over a month, closing.
