### ISSUE TITLE
Replacing sqlite3 with the QTSQL module

### ISSUE THREAD

**Issue by Gloorf** [xyzz/acquisition#117]
Acquisition has a really limited use for sqlite3, so the change shouldn't be too hard ; an example can be found in the pullrequest by borndead (see [acquisition.pro](https://github.com/xyzz/acquisition/pull/108/files#diff-3463d47e11a5e113e4a14413cee010cf), [datamanager.cpp](https://github.com/xyzz/acquisition/pull/108/files#diff-2ed70806b3a6af060c59730d3917e2e2), [datamanager.h](https://github.com/xyzz/acquisition/pull/108/files#diff-8be73878b3b754db9d6166990a5499e3)). I don't agree with his modification (it's imo better to stick with std::string for parameters & return value, except if we change *everything* in acquisition), it would be easy to change.

The only downside with that is we'll have to juggle between QString and std::string, but since sqlite3 is in C we already kinda does that, between char* and std::string.

**Comment by xyzz** [comment]
Is there any reason to use Qt's sqlite instead of shipping with our own? Also converting std::string to QString will result in a copy of the string being made, which can be quite big (I have about ~5MB of JSON in my Standard league stash).

**Comment by Gloorf** [comment]
It removes C code (it's better to use strictly C++ code in a c++ project imo) and an external dependency. Not saying it's strictly better, but it should probably be considered. Didn't knew about the conversion, it is like that both way ? (ie QString -> std::string)

**Comment by xyzz** [comment]
Yes it's like that both ways. I don't want to depend too much on Qt outside of GUI stuff (well, I still do, for example by using QNetworkManager). This way if one day I decide to move away from Qt or port to another platform with a separate GUI toolkit we don't have to suffer too much. sqlite works pretty much everywhere. I also don't see the problem of using a C library in C++ code.

**Comment by Gloorf** [comment]
>I don't want to depend too much on Qt outside of GUI stuff (well, I still do, for example by using QNetworkManager)

I understand, although i don't completely agree (i see Qt as a GUI library and a framework who makes C++ a less horrible language to use)
> I also don't see the problem of using a C library in C++ code.

I don't think there is any real programmation problem (well, i assume you could get some if you do things dirty but it's not the case here), it's more to keep things clean : better to use only function from C++, and limits the number of cast as much as possible (it's the same problem with QString & other QT "native" type : if you choose to use std::string, you need to stick with it everywhere). That beeing said, it's not much a deal :)
