### ISSUE TITLE
Acquisition can't update Shop

### ISSUE THREAD

**Issue by Autoritate** [xyzz/acquisition#119]
Hi there

I installed Acquisition and set it up like I saw in 2 description videos I found on youtube. I can login with either steam or via sessionid perfectly fine (it loads my tabs and stuff); it won't work with login/password tho (it won't even load first tab) but I don't care. I'm fine with two methods anyway. 

I set up my shop and I appear in Acquisition as online with control.poe.xyz, too. Everything could be fine but for some strange reason it won't be able to update my shop (Yes I know I only have to copy in the thread id digits rather than the whole link). 

Do I miss something crucial here?

Errors and warnings will be printed here
ERROR 2015-08-10T00:07:03.157 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. 
ERROR 2015-08-10T00:07:08.724 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. 

Any help is much appreciated, thank you. I did some research but didn't find anything helpful so far.

**Comment by xyzz** [comment]
your thread id is invalid, probably account you're logged in and account that created the thread are different so you can't edit it

**Comment by Autoritate** [comment]
Uhh, well. I'm looking into that. But I only have one steam account as well as one poe forum account... I'll try to figure that one out. 

Thanks for your super quick response :)

**Comment by xyzz** [comment]
you should log into poe website using your steam account

**Comment by Autoritate** [comment]
Oh, yeah. I just found out, too. That's a tricky thing going on there. It works now properly.

Thank you for your fast help, kind sir :)
