### ISSUE TITLE
Bug: Newly bought stash tabs do not appear in acquisition

### ISSUE THREAD

**Issue by Brentmeister** [xyzz/acquisition#120]
Repro:
Have existing items for sale in Acquisition
Open the shop and purchase new tabs
Go to Items->Refresh in Acquisition

Expected Result:
Newly purchased tabs appear in Acquisition

Actual Result:
Newly purchashed tabs do not appear in Acquisition

Hypothesis:
Acquisition saves the number of tabs you have and only refreshes up to that total number. Instead, it should check if there are new tabs first.

**Comment by Brentmeister** [comment]
Dug through the code. I think it's a bug where the API doesn't immediately update the number of tabs. The number of tabs I actually have is 29.

QUERY: https://www.pathofexile.com/character-window/get-stash-items?league=Warbands&tabs=1&tabIndex=1
Result: {"numTabs":23,"items":[...]}

QUERY: https://www.pathofexile.com/character-window/get-stash-items?league=Warbands
Result: {"numTabs":23,"items":[]}

Query: https://www.pathofexile.com/character-window/get-stash-items?league=Warbands&tabIndex=23
Result: false

If you guys have a relationship with GGG you might point this out.

**Comment by xyzz** [comment]
Have you put any items into the new tabs?

**Comment by Brentmeister** [comment]
Yeah there are items there. The tabs still haven't come up on the endpoints.

**Comment by xyzz** [comment]
You should try contacting GGG support, they might help.

**Comment by Brentmeister** [comment]
It finally updated, not sure what it took.

**Comment by emartinos** [comment]
have same problem. Takes a while
