### ISSUE TITLE
Organize Shop by Buyout with Spoilers

### ISSUE THREAD

**Issue by sovyn1** [xyzz/acquisition#126]
Hi guys :)

I have absolutely no knowledge of c++ but I really wanted acquisition to sort my shop by buyout via spoilers on the PoE forums. I figured the only way it would get done is by doing it myself.

Why is this important? Because there is a 50,000 character limit for a shop post and it's a huge waste of characters to repeat the same buyout line for every single item. Also the spoiler method allows for display of six items across rather than just one. Looks much better. Third and less important is the forum thread is much more useful for the occasional human forum browser. 

Here is my ridiculous hackjob:

in shop.cpp replace this:

	void Shop::Update() {
		shop_data_outdated_ = false;
		std::string data = "[spoiler]";
		for (auto &item : app_.items()) {
			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			data += item->location().GetForumCode(app_.league());

			data += BuyoutTypeAsPrefix[bo.type];

			if (bo.type == BUYOUT_TYPE_BUYOUT || bo.type == BUYOUT_TYPE_FIXED) {
				data += QString::number(bo.value).toUtf8().constData();
				data += " " + CurrencyAsTag[bo.currency];
			}
		}
		data += "[/spoiler]";

		shop_data_ = Util::StringReplace(shop_template_, kShopTemplateItems, data);
		shop_hash_ = Util::Md5(shop_data_);
	}

With this:

	void Shop::Update() {
		shop_data_outdated_ = false;
		std::string data = "";

		data += "[spoiler=\"Individually Priced\"]";
		for (auto &item : app_.items()) {
			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(((bo.value == 1 || bo.value == 2 || bo.value == 3 || bo.value == 4 || bo.value == 5 || bo.value == 7 || bo.value == 10 || bo.value == 15 || bo.value == 20) && bo.currency == CURRENCY_CHAOS_ORB) || (bo.value == 1 && bo.currency == CURRENCY_ORB_OF_FUSING))
			   continue;

			data += item->location().GetForumCode(app_.league());

			data += BuyoutTypeAsPrefix[bo.type];

			if (bo.type == BUYOUT_TYPE_BUYOUT || bo.type == BUYOUT_TYPE_FIXED) {
				data += QString::number(bo.value).toUtf8().constData();
				data += " " + CurrencyAsTag[bo.currency];
			}
		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 1 fuse\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 1)
				continue;
			if(bo.currency != CURRENCY_ORB_OF_FUSING)
			   continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 1 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 1)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
			   continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 2 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 2)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 3 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 3)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 4 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 4)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 5 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 5)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 7 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 7)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 10 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 10)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 15 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 15)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		data += "[spoiler=\"~b/o 20 chaos\"]";
		for (auto &item : app_.items()) {

			if (item->location().socketed())
				continue;
			Buyout bo;
			bo.type = BUYOUT_TYPE_NONE;

			std::string hash = item->location().GetUniqueHash();
			if (app_.buyout_manager().ExistsTab(hash))
				bo = app_.buyout_manager().GetTab(hash);
			if (app_.buyout_manager().Exists(*item))
				bo = app_.buyout_manager().Get(*item);
			if (bo.type == BUYOUT_TYPE_NONE)
				continue;

			if(bo.value != 20)
				continue;
			if(bo.currency != CURRENCY_CHAOS_ORB)
				continue;

			data += item->location().GetForumCode(app_.league());

		}
		data += "[/spoiler]";

		shop_data_ = Util::StringReplace(shop_template_, kShopTemplateItems, data);
		shop_hash_ = Util::Md5(shop_data_);
	}

Example shop: https://www.pathofexile.com/forum/view-thread/967550

Obviously this only works with the currencies/values I personally consider useful and common. Everything else would get lumped into the 'Individually Priced' spoiler as this stands. A better implementation would automatically take the tab-wide buyouts and join them if they are the same and output one spoiler per unique buyout price and place all tab contents that match into that one spoiler.

**Comment by Gloorf** [comment]
The bug with multiple shop has been fixed (and there should be a release with the bugfix in a week or so), so this wouldn't be very useful. If you want it though, head over to https://github.com/Novynn/acquisitionplus, Novynn is currently working on this :)

**Comment by sovyn1** [comment]
Novynn is currently working on an organized shop? Or just multiple shop function? They are two completely different things IMO. Anyway my hack works for me, maybe it will help someone who wants a nicer shop page.

**Comment by Gloorf** [comment]
An organised shop, with a template (like you can do in procurement)

**Comment by xyzz** [comment]
I think the best way to implement this feature while having both multishops and tab-wide buyout history is to first get all items with buyout/prices, sorted by buyouts. Then we start by creating the first b/o spoiler with the price of the first item in the sorted list, after that we incrementally add items until the shop is full (over 50k characters) or we've added all items with the first item's price (then switch to the next price). This way the shop shouldn't be too hard to generate or split between multiple forum threads.

**Comment by Gloorf** [comment]
Started [here](https://github.com/Gloorf/acquisition/commit/bd7253019f3ff7289e862feb1bf831d80525ff3e) (only sorting items for now). Not completely satisfied with the solution (it feels dirty to create a struct just for that, but other solution i knew of seemed dirtier). It's pretty fast for me (5ms on average), but i don't have that much items in my shop (210, for 26k character on the forum).

**Comment by xyzz** [comment]
What other solutions have you considered? 5ms for sorting 210 items is crazy slow. Perhaps try removing `std::shared_ptr<Item> item;` from the struct, maybe it adds some overhead.

**Comment by Gloorf** [comment]
My calculations were wayy off, sorry about that. Ran 10'000 times the code, and it took 24'110ms for the for part, 1'706ms for the sort part. It gives us 2.5ms for the total, with the for beeing the factor. It's also good to note that since we already got the buyouts, we don't need to get them again in [the next for](https://github.com/Gloorf/acquisition/blob/organize_shop/src/shop.cpp#L101-L125). It's actually pretty fast

For the others methods, i could : 
* Use an external function instead of the operator overload in the struct
* Use another struct & overload () instead of <
* Use another vector<int> [1..n], sort a std::vector<Buyout>, change the order in the vector<int> and apply that to the std::vector<Item>
* According to a quick google search, a fairly complex manipulation involving templates & multiple operator overload. I'm not well versed in c++ and this was hard to understand, put this solution away.

The problem we have is that we need first to get all the buyout anyway, since the buyout isn't a part of the Item class (and it would be too complicated to put it inside the Item class, especially for tabwide buyout), and it isn't part of the Item class (we have at least 2 std::vector to sort the same way based on 1).

**Comment by xyzz** [comment]
have you tried removing item shared_ptr as I suggested?

**Comment by Gloorf** [comment]
Forgot to do that, 23'208 ms for the for, 872 ms for the sort (around two time less).
According to [wikipedia](https://en.wikipedia.org/wiki/Sort_%28C%2B%2B%29), sort is t worst a complexity of O(n*log(n)), so it's almost linear ; so we should be good even with a lot of items.

**Comment by xyzz** [comment]
Alright, can you commit your benchmark code so I can check it out too?

**Comment by Gloorf** [comment]
See https://github.com/Gloorf/acquisition/blob/organize_shop/src/shop.cpp#L89-L113 (the commit are kinda messed, not super clear)

**Comment by sovyn1** [comment]
Glad someone who can code and is more familiar with the program is taking a look at this. :)

**Comment by xyzz** [comment]
Okay, two basic improvements would be move `AugmentedItem tmp = AugmentedItem();` outside the `for` and change `BuyoutManager::ItemHash` signature to `const std::string &ItemHash(const Item &item) const;` (actually this method is super useless so just changing all its invocations to item.hash() and then removing it would be even better).

**Comment by Gloorf** [comment]
I've slighty changed [the benchmark](https://github.com/Gloorf/acquisition/blob/organize_shop/src/shop.cpp#L80-L125) (do the 10k iterations on the whole function instead of just the std::vector<AugmentedItem> population & sort) and made your 2 improvement. Went from ~46'000ms to 42'000ms (so around 10% better). 

I've made the same benchmark on the non-struct Shop::Update(), and it took 38'000 ms (+-500 depending on the couple of tests i've made). So it's a difference of 10% between this and the new improved version, not much imo.

Considering sort is a O(n * log(n)), even with 10'000 items (and that's a shitton of items ; 70 tabs filled with items taking only 1 space) it would take (at worst) ~87 times the time it took for my 200 items. So we are speaking of 38*87 = 3306 ms before, and 42*87 = 3654 ms after. That's 300 ms in the most extreme case. For most player, it will be (way) less than 50 ms.

**Comment by Gloorf** [comment]
Changed the code to generate spoilers for all items ([commit](https://github.com/Gloorf/acquisition/commit/2dcaa7fb03c1daf3fedfffb663a854c5ccd24f7c)). It seems to works well with multi-thread (just add to lower the character limit cause i'm at way less than 50k) : https://www.pathofexile.com/forum/view-thread/1386098 & https://www.pathofexile.com/forum/view-thread/1119244/

**Comment by xyzz** [comment]
Cool, is it ready to be merged? Can you pull request it?

**Comment by sovyn1** [comment]
Great work Gloorf! :) Do you think it's necessary to place the buyout spoilers within an outer spoiler?

**Comment by Gloorf** [comment]
It doesn't change much, imo. I can remove it pretty easily if needed (just remove the [spoiler][/spoiler] from [shop.cpp:l134](https://github.com/Gloorf/acquisition/blob/shop_spoiler/src/shop.cpp#L134)
