### ISSUE TITLE
Can't select different prices for exact same items

### ISSUE THREAD

**Issue by rockmassif** [xyzz/acquisition#132]
I have 2 Vaults of Atziri in my stash, and somehow, by luck, they both have the exact same rarity roll. And when I try to change the price of one, other changes too automatically.

Problem is I don't wanna sell both, I just wanna sell one. If I chose ignore, they both get ignored. If I set a price for one, other has that same price tag too.

Not sure this is intentional, but kinda seemed like a bug to me.

**Comment by xyzz** [comment]
Possibly will be fixed by #75.

**Comment by leTensai** [comment]
i am facing the same problem with my mirrored 6Ls

**Comment by xyzz** [comment]
Fixed in next update, you will need to put them to separate tabs though.
