### ISSUE TITLE
Is there a way to not have an item for sale when i've assigned a bo for a tab?

### ISSUE THREAD

**Issue by mooberto** [xyzz/acquisition#135]
I dont have many stash tabs and I've just got one tab for uniques. so I set it to a bo and assign prices for various uniques that are more/less than the bo. But I can't seem to have an item excluded from the bo. Having the item set on ignore doesn't seem to work.

Thanks for any help you can provide. The program is amazing and so very useful.

**Comment by Gloorf** [comment]
As far as i know, you can't. What you can do is put a super high invidual buyout on the item you don't want to sell (not the best, but it should work)

**Comment by xyzz** [comment]
Maybe we should add a new option that will actually ignore the item and rename the previous to 'Inherit'. So we will have 'Buyout', 'Fixed price', 'Ignore', 'Inherit'. 'Inherit' is assumed if no buyout exist in the BuyoutManager. 'Ignore' now will actually be saved to 'BuyoutManager'. This also should help #72 (the "add a way to clear item individual buyout so it respects tab-wide buyout" part), #75. However maybe this naming is going to be confusing for the users, what do you think?

**Comment by Gloorf** [comment]
I think we could have an 'inherit' buyout choice, not by default, but simply available when you want to remove an individual buyout in a tab-wide buyout. It would be less confusing for the user imo

**Comment by conetopia** [comment]
Yes set it to "no price" ....
Or buyout [0]
:D

**Comment by ericsium** [comment]
You can do this as of #267 - just set to [ignore].
