### ISSUE TITLE
error: "Error while submitting shop to forums: Failed to find item. Did you specify the correct location and x y?"

### ISSUE THREAD

**Issue by JSOdin** [xyzz/acquisition#137]
tried making new thread,  restarting both the game client + acquisition after 1 hour of not touching any items in on my characters.  from what I can understand acquisition generates a shop template from the buyouts you set within the program, and updates your respective shop thread.  If you set acquisition to refresh your stash tabs to keep up to date with the game account, the generated shop template should only consist of items that exist.  this error persisted during the last couple weeks. I'm not sure if its a pathofexile forum or acquisition issue.

**Comment by R3ality** [comment]
I'm experiencing the same issue. As JSOdin pointed out, it appears that the shop data still includes items which are no longer in the inventory (that you've sold).
Presumably the shop data for the forum post is not getting re-generated after a refresh and before posting/copy-to-clipboard.

To recreate: 1. Add a buyout value to any item. 2. Remove the item from that stash location. 3. Refresh and copy-paste shop data in Acquisition - item is still included.
