### ISSUE TITLE
Weird bug. Lost all my prices.

### ISSUE THREAD

**Issue by timtitibu** [xyzz/acquisition#139]
So this is how it looks after I noticed the problem and restarted Acquisition - http://i.imgur.com/Eiqs9G2.png
Steps to reproduce (evertything as I always do): 
- I logged in by PHPSESID (I didn't interact with my forum account while the program was loading)
- I got an error (i think it was the same one as on the image, but I might be wrong)
- I noticed no prices and weird look of items, so I restarted Acquisition.

Item titles still have the same format no matter what i do - <<set:MS>><<set:M>><<set:S>>[Item name]
And I also get automatically generated whispers from poe.trade with items names in the same format.

PS. love the program very much, but it feels sad losing few hours of price checks :(

**Comment by xyzz** [comment]
#138
