### ISSUE TITLE
Searching your items by mods (needs a tweak)

### ISSUE THREAD

**Issue by Kanameclan** [xyzz/acquisition#142]
Could you maybe put in a dialogue on the drop down menu where we can type and find the mod we want to add to our search , the way it is on poe.trade ? The click and manually looking through a huge list without being able to type anything in to pull the mod up quickly is inconvenient as it is :)

**Comment by mythril** [comment]
also there are tons of missing mods

**Comment by Kanameclan** [comment]
Thank you for fixing this !! xoxo
