### ISSUE TITLE
Please add portable mode

### ISSUE THREAD

**Issue by dumpsters** [xyzz/acquisition#150]
^title^

I like to keep my PoE stuff in my USB stick so I have the skilltree planner and other tools all in one place everywhere I go.

My suggestion is a checkbox during installation that decides if the installation will be portable or not, portable version would save stuff to a local folder in the installation directory like the skilltree planner.

Thanks.

**Comment by xyzz** [comment]
You can use https://github.com/xyzz/acquisition#command-line-arguments to specify the data directory.

**Comment by dumpsters** [comment]
I guess I should've read the readme first.

Still, I think a portable option in the setup would be easier for tech illiterate people.

**Comment by xyzz** [comment]
I don't think the portable mode in setup would work well -- the setup is going to write to the registry anyway. What could work is two packages, a setup .exe and a portable .zip perhaps, however I'm not willing to maintain this unless there's a large demand. Setup is easier for most users as you don't need to copy your data over when updating Acquisition.

**Comment by dumpsters** [comment]
Your call
