### ISSUE TITLE
Cannot update shop

### ISSUE THREAD

**Issue by platinumfetus** [xyzz/acquisition#156]
I receive the following error

ERROR 2015-10-03T03:52:03.015 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. 

All information was correctly entered into the program and setup on the fourms.

**Comment by xyzz** [comment]
see https://github.com/xyzz/acquisition/issues/119

**Comment by platinumfetus** [comment]
I still receive the error after logging into both the forums and acquisition in steam.  I created a new thread while logged in with my steam account and still get the error,

**Comment by platinumfetus** [comment]
ok i got it to work thank you for responding.
