### ISSUE TITLE
acquisition 3.0.0.b? update, no vaal orb ?

### ISSUE THREAD

**Issue by conetopia** [xyzz/acquisition#157]
I guess 3.0.0.a updated to 3.0.0.b for the new 2.0.4 poe patch that released the new new 1 month flash back leagues. 
apparently vaal orb is not a thing.
Would like it to be added to acquisition.

**Comment by conetopia** [comment]
noticed armour / whetstones / scrolls gone too

**Comment by xyzz** [comment]
Merged in #90
