### ISSUE TITLE
Don't collapse expanded tabs when items are refreshed

### ISSUE THREAD

**Issue by xyzz** [xyzz/acquisition#16]

**Comment by GrappigPanda** [comment]
xyzz, you might need to re-examine this issue. Then again, there seems to be some persistent, underlying issue here, as all of my tabs automatically expand on update.

**Comment by xyzz** [comment]
>as all of my tabs automatically expand on update.

This one is actually by design, tabs are expanded if there are too few items (where "too few" is arbitrarily defined).

**Comment by Tvangeste** [comment]
But what is the reason for such design? It is a rather big annoyance when the tool keeps expanding and overriding user's preferred state.
