### ISSUE TITLE
item mods

### ISSUE THREAD

**Issue by yukatree** [xyzz/acquisition#165]
Just a suggestion, 
When you click an item and you see all its mods on the right, would it be possible to display what tier and prefix/suffix mod each one is. This would help me enormously when pricing items, knowing if it can have a life roll master crafted makes a big difference.

**Comment by xyzz** [comment]
There's no good way to figure what tiers the mods are, unless GGG adds this information to their API I'm not going to implement it. If somebody does this and makes a pull request I'll merge it of course.
