### ISSUE TITLE
Ampersand it shop thread title gets repeated every shop update

### ISSUE THREAD

**Issue by xyzz** [xyzz/acquisition#173]
For example, we can end up with "Infinity Tortellino Stap &amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp; Shap"

**Comment by thild42** [comment]
I pushed a PR #201 solving the problem.

**Comment by xyzz** [comment]
Thanks for the fix.

**Comment by thild42** [comment]
No problem. I'll be taking a look at the **build** issue.
