### ISSUE TITLE
Why tabs don't stay collapsed?

### ISSUE THREAD

**Issue by vibrasphere** [xyzz/acquisition#174]
Each time you refresh or update shops or whatever, it always auto-expands all tabs for no reason. If I collapsed one tab, I want it to stay collapsed until I decide to expand it.

I'm talking about tabs that are set to Ignore and not available for shop/trade. They should always stay collapsed if I collapsed them manually and not expand.

Cheers

**Comment by GrappigPanda** [comment]
See: https://github.com/xyzz/acquisition/issues/16

**Comment by vibrasphere** [comment]
Doesn't really solve anything. Plus my tab is 50% full.
