### ISSUE TITLE
Prices lost if item is moved

### ISSUE THREAD

**Issue by aiolos01** [xyzz/acquisition#175]
With the new version (the second v0.4) item prices seem to get lost when they are moved to a different tab or character. If an item is already priced on that tab or character then the application remembers it. If not then the item gets no price when moved.

**Comment by xyzz** [comment]
This is intended.

**Comment by aiolos01** [comment]
It didn't work like that in the past and I didn't see anything about it in the changelog.
This is very inconvenient, please make an option to go back to the old behaviour for those of us who want it.

**Comment by xyzz** [comment]
Supporting multiple options is too much work. The proper fix for that issue can only come from GGG if they add unique IDs to items.

What's your use case, why do you need to move priced items?

**Comment by aiolos01** [comment]
I have 17 stash tabs and most of them are taken up with stuff for my characters. When I find new loot I place them in a temp tab, price them all together and move them to whichever mule character has space left.
Even if I move them first and price them later there is always need to move things around to use space efficiently depending on what I find and what gets sold.
For example now I have emptied a character and want to move priced stuff there. I have to note the prices, move them and reprice them.
What I don't understand is how this has worked so far without unique IDs. Whatever you did seemed to work fine. Why change it ?
