### ISSUE TITLE
Can I remove the Attribute-Pictures in the new version?

### ISSUE THREAD

**Issue by RodWhiler** [xyzz/acquisition#177]
I really appreciate the try to make the GUI look more colorful and neat. Still I prefer the simple style of the former version, Can I somehow keep the newest version of acquisition and still benefit from the attribute-list in font-style instead of the image? Thank you for your great work.

**Comment by xyzz** [comment]
Why do you prefer the old style?

**Comment by RodWhiler** [comment]
For me it is much easier to catch all the attributes when I have a classical font and there is less "distraction". Don't take me wrong but that new "stats window" to me appears a little bit alienated among the otherwise simplistic (and actually really awesome ^^) data-base style. Btw. this "simplistic style" was one of the main reasons why I chose Acquisition over Procurement when I wanted to set up a shop for POE for the very first time.

**Comment by fljsdbd** [comment]
Hi i prefer the old version too. Because sometimes the gear image just expend the window size and makes the price setting bad disappear. So i have to maximize the window or minimize it and then open again to find out the missing price setting bar

**Comment by xyzz** [comment]
Fixed by cc4802a407a584bbde5c27549898f8366b5470e2
