### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by UlrichVonRekkenin** [xyzz/acquisition#178]
Add counter for currency, I mean you type, for example, **"Orb of Fusing"**, it exactly matchs with currency list and at right side notification appears **"You have # Orb of Fusing"**.

**Comment by xyzz** [comment]
There are already two ways to do that: 
1) Type "orb of fusing" in the search box and the tab title will show you how many orbs you have
2) Go to "Currency" -> "List currency"

**Comment by UlrichVonRekkenin** [comment]
Ok, I mislooked this one.
