### ISSUE TITLE
Add the option to Automatically bump threads

### ISSUE THREAD

**Issue by Illviljan** [xyzz/acquisition#179]
I would like to be able to automatically bump the thread every 60 minutes. Preferably it should be activated as default.

See these links for suggestions how to solve it:
https://www.reddit.com/r/pathofexile/comments/3f0hsq/what_to_do_about_price_fixing_on_poetrade/ctlw0y3
https://github.com/Novynn/acquisitionplus

**Comment by xyzz** [comment]
Are you willing to contribute the code that does it? This option shouldn't be enabled by default.

**Comment by thirdy** [comment]
> This option shouldn't be enabled by default.

why?

**Comment by xyzz** [comment]
Because people are used to current behavior and would expect Acquisition not to post in their shop thread by default.

**Comment by xyzz** [comment]
no response, closing
