### ISSUE TITLE
Jewels from tree

### ISSUE THREAD

**Issue by STanli** [xyzz/acquisition#182]
Didn't see jewels from tree. Can u fix it?

**Comment by xyzz** [comment]
what do you mean?

**Comment by STanli** [comment]
I want to sell jewel socketed in my passive skill tree

**Comment by TaigaTenori** [comment]
Yeah that would be useful, currently you can't search for them, nor set a b/o when they're socketed.

**Comment by xyzz** [comment]
impossible as they cannot be linked on forums
