### ISSUE TITLE
Can't find char name and can't fetch items

### ISSUE THREAD

**Issue by M4A1Silenced** [xyzz/acquisition#186]
Errors and warnings will be printed here
 WARN 2015-11-14T20:58:38.368 Can't extract selected character name from the page 
ERROR 2015-11-14T20:58:38.718 Can't even fetch first tab. Failed to update items.
I tired reinstalling
I play at standard
OS win10

**Comment by xyzz** [comment]
are you using steam with poe?

**Comment by M4A1Silenced** [comment]
Nope I only use email and session id

**Comment by M4A1Silenced** [comment]
Yes I use steam with poe
I tried using the steam login and now it works
