### ISSUE TITLE
can't extract selected character name

### ISSUE THREAD

**Issue by Hiwashi** [xyzz/acquisition#189]
I keep getting this message on the event log:

Errors and warnings will be printed here
 WARN 2015-12-12T19:42:34.625 Can't extract selected character name from the page 

and have no idea what may be causing it.

**Comment by LarsGoesRawr** [comment]
Similar Problem for me. Everything was working fine until a few minutes ago.

 WARN 2015-12-17T09:39:52.416 Can't extract selected character name from the page 
ERROR 2015-12-17T09:39:53.106 Can't even fetch first tab. Failed to update items.

**Comment by xyzz** [comment]
Do you still have this issue? Are you logging into the correct account?

**Comment by LarsGoesRawr** [comment]
Hi, Ive been getting random Warnings and Errors. Could be connection related as my ISP has an international cable break and is getting congested.



On Dec 22, 2015, at 07:54 PM, xyzz <notifications@github.com> wrote:

Do you still have this issue? Are you logging into the correct account?

**Comment by MCorrea92** [comment]
I would like to say that I'm having the same issue:

 WARN 2015-12-28T17:44:05.423 Can't extract selected character name from the page 

**Some extra information:**
1. I've checked my login information and it is correct.
2. Thread is updating fine.
3. I'm not showing up online at poe.trade (I have my Control URL set up)
4. The program is fetching my tabs fine.
5. Reinstalled it, but it didn't fix.

**Comment by asdzxcham** [comment]
I have the same problems just exactly like what MCorrea92 described. 

Here's what I did:

Reinstalled Acquisition 
Logout my account on POE website, cleaned the cookies, then logged in.

But it seem that the problems remained still.

**Comment by tpiardi** [comment]
Same error here.

**Comment by ericsium** [comment]
Do you have stream account or non-steam?  Or both that you switch between?  I'm not familiar with the authentication code but seems like maybe a bug in caching authentication related information.

Can you reproduce?  Switch beetween using SSID and login/pass with consistent results?
