### ISSUE TITLE
Fails to start up on Linux

### ISSUE THREAD

**Issue by GregSutcliffe** [xyzz/acquisition#191]
First, thanks for the awesome tool that supports my platform of choice :p

On 0.4a I'm getting the following error after logging in:

```
[greg:~/acquisition-0.4a]$ ./acquisition                             
QObject::connect: invalid null parameter
ERROR 2015-12-15T02:14:38.004 Can't even fetch first tab. Failed to update items. 
```

Not sure what else to do for debugging - was working fine during Flashback. No extra logs in log.txt. Any cmdline flags I can use?

**Comment by xyzz** [comment]
You should use the master branch, not the 0.4a tag.

**Comment by GregSutcliffe** [comment]
Looks good - sorry for the noise. Thanks again for the awesome tool!
