### ISSUE TITLE
Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid.

### ISSUE THREAD

**Issue by PumpFIST** [xyzz/acquisition#196]
ERROR 2015-12-23T18:06:14.022 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. 

Those errors keeps getting spamd. It has workd perfectly fine before for a long time. THis all of a sudden started to happend on the new hc talisman league as my 43 stash tabs is getting filld up.
Ive tried reinstalling aqusition. amde new shop threads, made 2 shop threads since it might betting too much, but i ahvent recived a prompt for needing to create another shop thread yet though.
Ive tried logging out making new session ids, ive even tried to message poexyz thingy again for anpther autoonline message but i get the same autoonline code as per usual.

dont know what to do. the green indicator showing how long untill the acquistion has updated shop just gets stuck at the verry start of the windows bottom bar icon.
Im alsow not connected to steam with PoE and have never been.

**Comment by xyzz** [comment]
Dupe of #192, also see https://github.com/xyzz/acquisition/issues/192#issuecomment-166987094 for a possible solution.
