### ISSUE TITLE
PHPSESSID in login screen

### ISSUE THREAD

**Issue by MLanghof** [xyzz/acquisition#202]
...maybe I'm missing out on the joke, but what was the point of [this](https://github.com/xyzz/acquisition/commit/cb26fac0ea220e04d1bf4b7b05cd57c696647fc2#diff-54fd71fecbff10d41fd3543acea6d445L114) change?

**Comment by xyzz** [comment]
It was changed when GGG *improved* their website while breaking the login in Acquisition (and other tools). Perhaps it could be changed back once they become more community-tools-developers-friendly?

**Comment by xyzz** [comment]
well geez it's 2016 already and there are still no improvements, I guess I'll just switch it back.
