### ISSUE TITLE
"Last Update" displays incorrectly when the next day rolls over?

### ISSUE THREAD

**Issue by DeadlyParadox** [xyzz/acquisition#208]
I put up items at 11:00ish PM, and when I checked the items the last update lists 1 day ago. There's no way that's correct. I use tab-wide buyouts, if that helps.

**Comment by xyzz** [comment]
what's "last update"?

**Comment by DeadlyParadox** [comment]
https://i.imgur.com/LxUzhuy.png

The last time the item was priced.

**Comment by xyzz** [comment]
Ok, can you check if this build fixes the issue: https://xyz.is/acquisition/bin/acquisition_setup_0.4b-issue-208.exe

**Comment by DeadlyParadox** [comment]
Sure thing. I think I might have to wait until about midnight to see if it fixed the issue.

**Comment by DeadlyParadox** [comment]
It seemed to be fixed as soon as I installed the build. The times on the items that were previously 1 day old became less than 24 hours. I'll check again at midnight.
