### ISSUE TITLE
Is there a way to download only certain tabs?

### ISSUE THREAD

**Issue by Haroldyolo** [xyzz/acquisition#211]
Hi,

I have a lot of tabs and updating takes ages. Is there any chance to download only certain tabs and ignore the rest or is that not implemented yet?

**Comment by wichtounet** [comment]
That would be a great addition to the tool. A simple list in a text file would be sufficient I think and it would make it much faster.

**Comment by wichtounet** [comment]
This was fixed by release of Acquisition 0.5
