### ISSUE TITLE
Support for QT4

### ISSUE THREAD

**Issue by wichtounet** [xyzz/acquisition#213]
Hi, 

I wanted to start playing with the code and add some features to the tool. 

I'm trying to compile it on Linux with QT4 and g++, but I have several issues. Is it expected to work ? 

I had to remove from the pro file:

    _CXXFLAGS += -Wno-inconsistent-missing-override

And change:

    CONFIG += c++11

into

    greaterThan(QT_MAJOR_VERSION, 4){
       CONFIG += c++11
    } else {
       QMAKE_CXXFLAGS += -std=c++0x
    }

I also had to remove includes to QtWidgets, I think it is not recommended to include it directly, but I may be wrong. 

For instance, at application.cpp:60, this line:

    connect(items_manager_.get(), &ItemsManager::ItemsRefreshed, this, &Application::OnItemsRefreshed);

must be replaced by:

    connect(items_manager_.get(), SIGNAL(ItemsManager::ItemsRefreshed), this, SLOT(Application::OnItemsRefreshed));

to compile. 

I have a lot of experience in C++ on Linux, but I don't develop on Windows, so I don't know if these changes can make sense for you on Windows with Qt5. If they make, I can try to make them all and try and then propose a Pull Request. Otherwise, I'll work on the fork directly. I can also try to use clang if if you think it is better supported by acquisition. 

Thanks

**Comment by xyzz** [comment]
Hi,

Why can't you just use Qt 5? It should work fine on 5.4, I haven't tested any earlier versions, so they also might work.

**Comment by wichtounet** [comment]
Hi, 

Because the Linux packages for the version 5 are terribly bloated. 

Anyway, I'll see what changes are necessary to make it work on QT4 and if it is not too much, I'll create a Pull Request.

**Comment by xyzz** [comment]
closing this issue too
