### ISSUE TITLE
Current Offer

### ISSUE THREAD

**Issue by eXecut1on** [xyzz/acquisition#214]
Can we please have a current offer tag? :)

**Comment by wichtounet** [comment]
If @xyzz is interested by this feature, I could propose a pull request for it.

**Comment by xyzz** [comment]
I suggest we first wait for the Ascendancy release so that in case GGG changes everything about the trade system and Acquisition becomes completely useless @wichtounet won't feel bad about implementing this feature.

**Comment by eXecut1on** [comment]
"in case GGG changes everything about the trade system and Acquisition becomes completely useless"
nice joke man :+1:

**Comment by wichtounet** [comment]
@xyzz Are you a prophet ? :D Never thought they would do so much in the first wave...

**Comment by xyzz** [comment]
¯\_(ツ)_/¯

**Comment by ericsium** [comment]
c/o was added with #267.
