### ISSUE TITLE
Not showing ONLINE on Acquisition.

### ISSUE THREAD

**Issue by ArwainOnBerserk** [xyzz/acquisition#221]
I honestly don't know how to fix it, i checked the automatically refresh online status and in the bottom corner it says that i'm Online, still when I try to find my items on poe.trade they are not listed on the Online, they're listed as i'm offline.

**Comment by ArwainOnBerserk** [comment]
anyone here ?

**Comment by luckyroiu** [comment]
I got the same problem like you aswell. Anything solved by so far?

**Comment by ericsium** [comment]
Please go through the [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) document and see if you have any luck resolving your problem.

Also check out [Auto-Online](https://github.com/xyzz/acquisition/wiki/Auto-Online).  The more specific you can be on what you tried etc... the easier it is to help.
