### ISSUE TITLE
Standard shop no longer updating

### ISSUE THREAD

**Issue by atlas305** [xyzz/acquisition#225]
I haven't updated my standard shop since Talisman started.  I acquired some boots on Standard so I went to post them.  The problem is my shop is no longer updating.  I tried pricing other items (scroll of wisdom 100 exalts) and it wont show up in the shop. (standard trading-selling)  I reset my computer, logged into the talisman and back, nothing is working.

My talisman shop on the other hand is working as intended. (talisman sc shops).

**Comment by ericsium** [comment]
Are you getting any error messages when you try to submit your shop?

Do you have any pending character names to change?
