### ISSUE TITLE
Problem with poe.trade not display my info correctly

### ISSUE THREAD

**Issue by Alekhoff** [xyzz/acquisition#227]
Hey, could you help me out with this problem, kinda hard trading when people cant see my name or see if im online.
Im using Acqustion, with a Online url.
 
Here is a screenshot of one of my items on poe.xyz http://imgur.com/vICoRjQ and i am online in aqcuisition: https://i.imgur.com/W2u6Bl0.png

**Comment by xyzz** [comment]
that's not an acquisition issue, report it to the poe.trade forum thread
