### ISSUE TITLE
Network error: SSL handshake failed (arch linux)

### ISSUE THREAD

**Issue by ccomly** [xyzz/acquisition#228]
Network error: SSL handshake failed

with sessionid login, tried making a fresh id, same thing

**Comment by ccomly** [comment]
timing out to get.acquisition.today
ehm some kind of dns issue?

**Comment by ccomly** [comment]
get an ip now atleast

**Comment by ccomly** [comment]
started working again magically, the site still wont load tho

**Comment by xyzz** [comment]
The get.acquisition.today site has been broken for a while, but that's not relevant. Closing since you said it's fixed.
