### ISSUE TITLE
Name column mismatch for standard tabs

### ISSUE THREAD

**Issue by hmathers** [xyzz/acquisition#229]
Very small issue with my Name column not having a #1 - all the tabs are numbered wrong as a result. Not sure if this is unusual but it throws me off a lot.
![untitled](https://cloud.githubusercontent.com/assets/16958255/12678099/1d20fcb6-c66b-11e5-9569-17cfecd06926.png)

**Comment by ericsium** [comment]
The format is:

#<stashId>, "<user_assigned_name>"

If you buy premium tabs you can change <user_assigned_name> to whatever you want.  Internally GGG identifies tabs by the stashId which really has no correlation to the user_assigned_name.  If you execute Shop->Copy shop data to clipboard and paste into a document.  You'll see it sets the 'location' for items based on the <stashId> number "Stash2" for tabs identified with \#2 which just happens to be first tab for some reason.  Maybe Stash1 was originally used for items on the character or something.

**Comment by hmathers** [comment]
Thanks for the explanation! I'll try to come up with a satisfying solution.
