### ISSUE TITLE
Don't upload any items

### ISSUE THREAD

**Issue by MrShady187** [xyzz/acquisition#231]
Hey, im new at this and I downloaded newest an any other versions, but Acquisition don't upload my items to any thread.
It just upload the "Shop template". So thread no. is correct. Items set to buyout with various prices, I got my online link and Acquisition show me online.
I don't get any error..It shows "Shop threads updated"
But no items there...
What to do?

**Comment by ericsium** [comment]
I'm not sure exactly, check out this video to make sure you did everything correctly:

https://www.youtube.com/watch?v=HeqU9jkWRy0

Also, if you're just starting you shouldn't touch the 'shop template' option - make sure the text field just says '[items]' and nothing else.  If you removed '[items]' it won't post your items.

Try making a new trading thread as described in the video.

**Comment by MrShady187** [comment]
Impossible :D I tried anything, just not this one :D 
I tried to remove anything on Shop template but it didnt work, reinstalled, nothing...
But now it works, omg tyvm..
