### ISSUE TITLE
Currency to Chaos as well as exalted

### ISSUE THREAD

**Issue by KCIV** [xyzz/acquisition#234]
Can we please have a selection to convert to chaos? instead of only exalted?

I was really wanting Acquisition to have the same functionality as procurement in regards to Currency tracking (and csv export)

**Comment by xyzz** [comment]
What functionality is present in Procurement that you're missing in Acquisition?

**Comment by KCIV** [comment]
specifically the tracking of your currency in inventory. It tracks your total value of currency in chaos (based on input ratios)

I was hoping Acquisition would have the same thing.

It has a currency of sorts but its based on exalt.

**Comment by Gloorf** [comment]
I'll look into that tomorrow (i need to go over the currency code cause it's a little buggy), but it's only a label anyway. If you want, you can put the value to chaos instead and read exalted as chaos (won't work if you need both currency to chaos and currency to exalted)

**Comment by KCIV** [comment]
Personally I would love that!!! The export to CSV is one of the main reasons I was looking at acquisition. 

I'm currently running output tracking my income and doing IIQ/IIR tests which these features specifically make easy to both graph,record, and track.

I'm not against exalt conversion however I rarely convert Alts into ex, most of the time I concern myself with chaos.

I wouldn't change the default, but possibly add a chaos or exalt conversion.

**Comment by xyzz** [comment]
Okay, can't you just imagine it says "chaos" in all places where it now says "exalted"?

**Comment by KCIV** [comment]
With some work yes, but since you can only enter in 2 decimals, converting values of .0143 to .01 makes for inaccurate conversions. For example exaults to chaos are either 100 or 50, (since the true value is .01XXX) the true conversion is closer to 70 so being off by values of 30 chaos is too much for me :/

Currently in procurment you can enter in the ratio Orbs X to Chaos X which allows easy currency formatting and conversions.

I'm not trying to complain or say Procurement is better, But adding its functionality to acquisition would make acquisition far superior for at least my purposes. (the export CSV is just the best feature!)

**Comment by Gloorf** [comment]
>Currently in procurment you can enter in the ratio Orbs X to Chaos X which allows easy currency formatting and conversions.

Hmm, that's not a bad idea, i'll do something like that i think

>I'm not trying to complain or say Procurement is better, But adding its functionality to acquisition would make acquisition far superior for at least my purposes. (the export CSV is just the best feature!)

Does export to CSV works for you at the moment ?

**Comment by KCIV** [comment]
Yea it saves a file which I can open, some of the formatting was a bit off but its easy to fix. Better than typing or copy pasting each value out. :)

**Comment by Gloorf** [comment]
Fixed by #236, we can close this one
