### ISSUE TITLE
Path of Exile Acquisition warning

### ISSUE THREAD

**Issue by rac503** [xyzz/acquisition#237]
First off, I'm not sure how to use this website and I hope I am submitting this issue in the correct location. I just jumped back on Path of Exile, haven't played in over a year, and decided i should start trading. i found out about Acquisition and immediately installed. Followed step-by-step instructions on how to get it started and as i opened the program it attempted to receive my stash but halted almost at 100%. It reached around 43 out of 46 then i kept getting warnings about non object response. i tried uninstalling acquistion and re-installing and copying/pasting url and thread # but still no luck. Any help would be appreciated. 
-Rac

**Comment by xyzz** [comment]
If you open your inventory on the website does it work? Try switching to the problematic tabs. If the issue persists while using the website, you should report it to GGG.

**Comment by rac503** [comment]
Yes i checked on the poe website and i can view all my characters and all my stash tabs and all tabs are up-to-date with items i placed in there moments ago.

**Comment by ericsium** [comment]
Do you happen to have any tabs with very unorthadox names (strange characters, spaces etc?) Since you got to 43/46 I'd check out later tab names and try renaming them to simple strings to test.

**Comment by rac503** [comment]
hmm.. i have a couple characters i haven't played in over a year so i have to change their names. and tab names i suppose i can simplify them and put them as 1,2,3,ect. i'll update when tested.

**Comment by rac503** [comment]
wow that worked. like i said i had a couple characters that needed updated and i changed the tab names, but im guessing it was the characters. thank you very much i really appreciate it!

**Comment by ericsium** [comment]
Great! Yeah, it definitely would have been the pending character name changes that would have caused this problem.
