### ISSUE TITLE
Missing "Increased Global Critical Strike Chance" in Mods search

### ISSUE THREAD

**Issue by shixish** [xyzz/acquisition#241]
There's only crit multi and crit for spells.

Looking at it with Acquisition 0.5

**Comment by shixish** [comment]
Are you accepting pull requests?

**Comment by ericsium** [comment]
Yes, we'll accept pull requests.  I notice this one is fixed so will close out.

**Comment by shixish** [comment]
Cool thanks. I'll see if I can contribute sometime down the road. Thanks for the great work you've been doing!

**Comment by ericsium** [comment]
Sure, thare are a number of enhancements open, prefereably add a note to relevent enhancement if you're looking into it.
