### ISSUE TITLE
In-game pricing handling

### ISSUE THREAD

**Issue by ericsium** [xyzz/acquisition#247]
Just wanted to get a thread going to try to discuss some needed implementation updates due to the recent in-game pricing changes.  It's possible that this is a bit premature as we don't yet know what else is coming but GGG seems to be clear that they are going to leave the existing trade mechanism in place and adding the new trade features on top of that.

We'll need to deal with this quickly though as it will be a problem I assume if conflicting pricing data gets posted through the forumns vs in-game?

1. It seems we're now going to need to 'honor' in game tab pricing and individual item pricing from the 'note' field.  This pricing will need to take priority over anything done through aquisition so I assume we'll have to treat in-game pricing as 'locked' from the tools perspective.

2. How should we handle items with in-game pricing as far as shop updates go?  I assume that it's not efficient for acquisition to post items with in-game pricing as they would be indexed twice by poe.trade but maybe this is not a big issue?  We can't control for example it other tools do this.  So do we just not add in-game priced items to shop threads?

3. From what I can tell the tab itself does not have an 'info' field like items, so the pricing info is part of the tab itself.  I think this is going to frustrate people as the width of the tab will take up so much space it will only be possible to see 3-4 tabs at once.  This is just an observation and a reason that people might like to continue to use an external tool.

You may be already looking into making these changes, if so let me know - otherwise I'd be willing to look into making updates to handle these issues.

**Comment by xyzz** [comment]
Why do we need to support import of items priced in-game? If they are priced in the game there doesn't seem to be any point to post them on the forums.

**Comment by ericsium** [comment]
Yeah, that's pretty much what I figured.  But we don't want people to be able to change the prices of in-game priced items in aquisition so we probably want to 'lock' those items so the pricing cannot be changed from within the aquisition tool (if it is priced in 'info' field' or tab priced).  Then update the code to ignore posting of these items.

**Comment by xyzz** [comment]
Feel free to implement that if you want, but I personally don't think it's very important -- if the user breaks things like that it's their fault.

**Comment by ericsium** [comment]
Implemented with #249.
