### ISSUE TITLE
Can't even fetch first tab. Failed to update items. 

### ISSUE THREAD

**Issue by OMimeault** [xyzz/acquisition#254]
This is what I see after refreshing the tabs.
http://i.imgur.com/qsSEsiv.png

**Comment by ericsium** [comment]
Yeah, I see it too - looking...

**Comment by xyzz** [comment]
Fixed, releasing a build in a moment.

**Comment by xyzz** [comment]
Actually that one is for Perandus, and the bug with the hardcore. If you still have the issue please reopen, it's possible the website was busy or something was wrong, either way it works fine for me.
