### ISSUE TITLE
Not showing/detecting/refreshing new public tabs.

### ISSUE THREAD

**Issue by vibrasphere** [xyzz/acquisition#255]
What i'm doing wrong? Content of my public premium tab (which is set to public and price each item separately) is not appearing in latest version of acq.

It does show what's in my other tabs, e.g. tab1 and char inventory.

No errors.

**Comment by ericsium** [comment]
Can you give more details?  What league, what is the tab names.  

Things to check try:
- do you have some filtering active?
- Maybe you're not 'refreshing' the tabs?  You select (check) tabs of interest and can 'refresh selected'.  This will refresh selected tabs and items.

You can enable 'auto refresh' with a time interval to automatically have tool do this.

**Comment by vibrasphere** [comment]
No, I'm doing all correctly. And configured correctly. And refreshing and auto set.

It finally updated tabs after restarting the program twice within 10 minutes.

**Comment by ericsium** [comment]
How many tabs do you have selected for refresh?  Was it in the middle of an update cycle possibly or throttled?

**Comment by vibrasphere** [comment]
10 minute long throttle? 10 tabs. 6 premium. Maybe servers lagging.

**Comment by ericsium** [comment]
Normally in game updates are visible to the API fairly quickly, it's also possible something was backed up on GGG's end and the changes took longer than usual to be API visible.

Anyway, let me know if behavior continues to be strange or if you can reproduce any problem behavior.

**Comment by ericsium** [comment]
Closing this issue - haven't seen other related problems so likely this this was a server problem.
