### ISSUE TITLE
path of exile acquistion not updating prices

### ISSUE THREAD

**Issue by rac503** [xyzz/acquisition#260]
just started new league and would like to start trading. downloaded and installed new version (0.5c) and inserted thread # and url properly. my character shows along with stash and items and there are no warnings but when i try and price an item (buyout/currency) and click on another item to continue pricing it doesnt update the price on previous item. im at a loss and tried updating all stash tabs and selected stash. i've used acquistion in past and when i priced an item it immediately updated item with the currency i selected... any help would be appreciated. thanks.
-Rac

**Comment by rac503** [comment]
solved! next to the currency selection is another box where i am suppose to placed number of said currnecy. dont remember using that in the past but sorry to waste time. thanks. 
-Rac

**Comment by ericsium** [comment]
Okay, glad you were able to figure this out.
