### ISSUE TITLE
URL Link points to Nginx on Debian

### ISSUE THREAD

**Issue by keeb** [xyzz/acquisition#263]
Browsing to http://get.acquisition.today/ leads you to the following page

![image](https://cloud.githubusercontent.com/assets/15742/13642841/e608dd3e-e5d2-11e5-8bb5-d2e367f3bf75.png)

**Comment by xyzz** [comment]
fixed

**Comment by keeb** [comment]
verified. invalidated cache and now get to the correct page.

**Comment by ericsium** [comment]
Hi keeb, I couldn't help but notice you work for Docker.  Can you check out this thread and post if you have any comments?

https://github.com/xyzz/acquisition/issues/257

I kind of came to the conclusion my best bet might be to use vagrant for this purpose but would appreciate your input.

**Comment by keeb** [comment]
@ericsium no worries, I think @psftw or @cpuguy83 would be the best people for you to talk to about this.

**Comment by cpuguy83** [comment]
For sure where Docker shines is building consistent environments regardless of infrastructure.
With Docker anyone can spin up the env w/o having to fire up a new VM to do it.

**Comment by ericsium** [comment]
For headless apps it seems to be true that docker is often most optimal.  For hosting GUI apps though it seems like full VM's are best as they can better encapsulate X11 and the windows managers and provide a consistent interface and relatively easy non-headless access through VirtualBox whether you're on windows or unix. 

In the time I spent searching I was having a lot of trouble finding out how to do this with docker.  Granted I haven't spent much time digging into this or been able to do much testing, if you have any thoughts or pointers though please let me know.

**Comment by cpuguy83** [comment]
@ericsium exposing X11 can be trickier when not on Linux, but is possible.
X11 listens on a socket (unix socket by default) which you can forward into the container.
For non-local environments (e.g. Mac->Docker) X11 can be setup to work over TCP (or you can proxy the unix socket)... but yes this does require some extra work.
