### ISSUE TITLE
Sorting Items

### ISSUE THREAD

**Issue by Savlik** [xyzz/acquisition#266]
Hi,
Is it possible to sort items (by name, iLevel, etc.)? If not, could you add it? It should be pretty simple since QTreeView has some default sorting functionality, just turn it on. 

Savlik

**Comment by ericsium** [comment]
I'll mark this as an enhancement.   If you're interested in QT development you're welcome to fork the project and submit a pull request for this feature.

In the meantime you might consider checking out the chrome addon 'Looty'. 

It excels at the task of sorting and filtering items.

https://chrome.google.com/webstore/detail/looty-stash-search-for-pa/ajfbflclpnpbjkfibijekgcombcgehbi?hl=en-US
