### ISSUE TITLE
Unable to use from multiple locations.

### ISSUE THREAD

**Issue by klannedoklan** [xyzz/acquisition#268]
Hello, 
This is a very useful tool, but I am playing Path of Exile from 2 machines and I want somehow to be able to maintain my forum post with consistency. With Procurement that was possible just by packing my folder and send it through the mail.
I have tried that with Acquisition 0.4a Plus and It didn't work.

**Comment by ericsium** [comment]
I don't know of any reason this wouldn't work with aquisition as well.  

Your aquisition data is stored at:

c:\Users\<user>\AppData\Local\aquisition

If you zip that up and replace that forlder at target computer I think it should retain all your buyouts.  Let me know if that doesn't work.

**Comment by ericsium** [comment]
#212 is another ticket discussing this same topic.

**Comment by ericsium** [comment]
I'm assuming this is resolved, please reopen if needed.
