### ISSUE TITLE
~b/o 7 jew - using ingame prenium tab

### ISSUE THREAD

**Issue by kishikouma** [xyzz/acquisition#278]
causes this error to endlessly repeat:
WARN 2016-03-22T14:52:10.412 Cannot map string: ' "jew" ' to currency type.  This should not happen - please report. 
 WARN 2016-03-22T14:52:10.412 Cannot map string: ' "jew" ' to currency type.  This should not happen - please report. 
 WARN 2016-03-22T14:52:10.413 Cannot map string: ' "jew" ' to currency type.  This should not happen - please report. 
 WARN 2016-03-22T14:52:15.985 Cannot map string: ' "jew" ' to currency type.  This should not happen - please report.

**Comment by Gloorf** [comment]
Thanks for the report, will be fixed in next release :)
I also checked, all other currencies match GGG naming scheme, so we're good here
