### ISSUE TITLE
Shop Threads Not Updating 

### ISSUE THREAD

**Issue by xxThraXxx** [xyzz/acquisition#282]
ERROR 2016-03-24T15:37:04.569 Error while submitting shop to forums: '[spoiler][spoiler=&quot; ~b/o  1 fuse&quot;][linkItem location=&quot;Stash27&quot; league=&quot;Standard&quot; x=&quot;0&quot; y=&quot;7&quot;][linkItem location=&quot;Stash30&quot; league=&quot;Standard&quot; 

                           (Giant wall of more of the same)

league=&quot;Standard&quot; x=&quot;10&quot; y=&quot;6&quot;][linkItem location=&quot;Stash41&quot; league=&quot;Standard&quot; x=&quot;0&quot; y=&quot;8&quot;][linkItem location=&quot;Stash41&quot; league=&quot;Standard&quot; x=&quot;3&quot; y=&quot;6&quot;][/spoiler][spoiler=&quot; ~b/o  15 chaos&quot;][/spoiler][/spoiler]' is more than 50000 characters long 

I am in Standard and have not been able to update threads via auto update since installing this version. Keep getting the wall of text above in the Event Log.
Have completely uninstalled/reinstalled Acquisition and repriced everything to no avail.

Some assistance would be appreciated, thanks in advance

**Comment by xxThraXxx** [comment]
Please disregard the above. Issue resolved itself after system reboot.

**Comment by ericsium** [comment]
I'm actually surprised  a reboot had any effect.  Posts have a 50,000 character limit which it seems you're bumping up against.  To fix you need to create another forumn thread and put multiple id's in when setting forumn thread.

You probably removed a few prices or renamed a tab to something shorter which temporarily fixed.

**Comment by xxThraXxx** [comment]
Hi. I have 3 forum threads and id's set up and only actually have items in
2 of them. I have been using Acquisition for approximately 6 months now and
this is the first time this issue has occurred. I made no pricing/tab
rename changes, but did however purchase a Currency Stash Tab just prior to
updating to 0.5e. I don't know if this may have affected things, but as I
said, once i did a system reboot (which I very rarely do) everything was
fine.
In any event, all is working as it should.

Thank you for your reply.

**Comment by ericsium** [comment]
Okay, thanks for the addional information.
