### ISSUE TITLE
Error while submitting shop to forums: Duplicate submission token has expired. Please submit the form again.

### ISSUE THREAD

**Issue by brlafreniere** [xyzz/acquisition#283]
Receiving this error in Acquisition:

ERROR 2016-03-25T11:31:52.244 Error while submitting shop to forums: Duplicate submission token has expired. Please submit the form again.

Also showing my status as Offline.

**Comment by ericsium** [comment]
Can you peruse [these threads](https://github.com/xyzz/acquisition/issues?utf8=%E2%9C%93&q=is%3Aissue+Duplicate+submission+token) and see if anything fixes the problem for you?  If something does work please reply saying it is now working for you and what fixed the issue.

If you still have issues please provide more information and make sure you've tried restaring the app, restarting your computer etc...

**Comment by brlafreniere** [comment]
Sure, I'll get back to you later.

**Comment by brlafreniere** [comment]
Haven't had any luck with those either. Not seeing the error currently, but still offline. Tried refreshing my tabs, checking/unchecking refresh online status, and I also tried re-installing Acquisition.

**Comment by ericsium** [comment]
Just to verify:

1. You entered full poe trade URL into 'Auto Online' in aquisition
2. You selected 'auto refresh online status'
3. You went in game (auto online requires you are running poe)

If you do all those thigns you should see 'online' in aquisition and your status as 'online' in poe.trade within 2-5 minutes.

**Comment by brlafreniere** [comment]
Hmm, well, I'm guessing it was the last step that did it, but it appears to
be working now.

**Comment by brlafreniere** [comment]
I seem to be getting the error still, although most importantly... I'm online now, thanks for your help.

**Comment by ericsium** [comment]
Closing.
