### ISSUE TITLE
acquisition index attribute set to '1' error

### ISSUE THREAD

**Issue by sebastien1031** [xyzz/acquisition#284]
Error while submitting shop to forums: An item with 'index' attribute set to '1' does not exist. Any idea how to fix this? also it wont link any of my items with the buyouts i set on them in acquisition. it shows them on xyz and says im online, but doesnt have the buyouts i set.

**Comment by ericsium** [comment]
This could happen if you force 'update shop at forumns' with stale tab data.  Normally if you do updates in game make sure to 'update checked tabs' before you force an update.  Else the data can be out of sync with the game data.

If that's not it can you give more info - what league, thread id, have you tried quitting/restarting acquisition, you're computer etc..?  If this gets resolved, even if you're not sure why please let me know.

**Comment by sebastien1031** [comment]
ive tried refreshing all the tabs and i even organized everything so all
the items i was selling are in one tab and refreshed again. im in standard
league and this is my forum shop.
 https://www.pathofexile.com/forum/view-thread/1632339

**Comment by ericsium** [comment]
Did you happen to modify Shop -> Shop Template?

Can you check that it just contains:

[items]

Try creating a new thread, make sure your forum shop thread is set to the new shop number.  If that doesn't work I't resetting aquisition settings as described in #276 as your database may be corrupted.

**Comment by sebastien1031** [comment]
Omg it was something in the template, i accidently put something in there.
thank you so much, you have saved the day. Thank you! Have a great day!

**Comment by ericsium** [comment]
Okay, great np!
