### ISSUE TITLE
Sorry to post this here, but not sure what else to do

### ISSUE THREAD

**Issue by joe7dust** [xyzz/acquisition#286]
I can't figure out how to contact ericsium, tried twitter but not even sure if they are the same person. Apparently with linux you can pull email from commits but I couldn't figure out how to do it in windows... anyways just wanted to add onto the issue that was closed: I don't think that a GGG solution would be good for the community in regards to my suggestion. It would still create headache for users trying to contact people on trades they aren't currently interested in. Since Acquisition spearheaded the auto-online feature and eventually that made its way into poe.trade site, it seems likely they might have to do it again for auto-offline if xyz is unwilling to do it.

**Comment by ericsium** [comment]
xyz is the original designer of aquisition, I'm a collaborator, so just help out on the project.  Anyway, see #285 - I just reopened it.  In general you can respond to github e-mails to append to issue or click on the 'view in github' in the main to return to the thread and add more comments even if it's closed.

**Comment by joe7dust** [comment]
Can reply if closed? Never seen this before lol. Thanks for your time.

Sent from Yahoo Mail on Android 
 
  On Sat, Mar 26, 2016 at 5:40 PM, Eric White<notifications@github.com> wrote:   
Closed #286.
