### ISSUE TITLE
[ERROR] Setup / unable to Launch

### ISSUE THREAD

**Issue by babbajagga** [xyzz/acquisition#287]
Unable to execute file: D:\Acquisition\acquisition.exe CreateProcess failed; 193. %1 is not a valid aplication of Win32.
![ffs](https://cloud.githubusercontent.com/assets/2865693/14065624/9a1dfb6c-f431-11e5-9763-85ca3a91b03c.png)

**Comment by ericsium** [comment]
Can you provide more information?  Was it working before or is this a new install?  Have you tried removing and reinstalling the application?

Why in your text do you refer to D:\Acquisition\acquisition.exe while the dialog is referring to something on F:\ with a different path?   Did you do something with shortcuts?  Can you reinstall and try standard location?

**Comment by xyzz** [comment]
Windows XP is not supported.

**Comment by babbajagga** [comment]
Hello,
I was using v.0.4b, worked fine.

the path refference is just because I copied that text from another topic with the same error on reddit iirc., but it was the same issue.

And yes, I have tried uninstalling and reinstalling it.

same outcome.
