### ISSUE TITLE
acquisition showing offline 

### ISSUE THREAD

**Issue by FCKNback** [xyzz/acquisition#288]
HI, i have a problem with acquisition showing offline and not auto-online on poexyzz . Already created new shop , deleted the other one , checked all URL/threadnumber things and still haven't found any solution. 
 
Thanks in advance for your help.

**Comment by ericsium** [comment]
Do you have POE  running on same computer the acquisition process is running on? 

It won't show you as online if you're not running POE.

**Comment by FCKNback** [comment]
Hey , i am of course running POE on the same computer , poexyzz and acquisition worked well till 2weeks a go where it can go online or offline completely randomly...(or it seeems it does).

**Comment by FCKNback** [comment]
OK , new thing , ran poe during the night . Just checked Acquisition shows "offline" but it seems it worked ..So still the same issue , it goes randomly online or offline

**Comment by ericsium** [comment]
Can you verify that auto-online is setup properly from this page and the related reddit post:

https://github.com/xyzz/acquisition/wiki/Auto-Online

You can also manually go to the webpage listed by your poe control id and set yourself online and verify that that works.

**Comment by FCKNback** [comment]
Been doing all kind of research , found the problem (poesessid doesnt work for me anymore) needed to log with steam login . The acquisition program though still shows "offline" but everything is fine .
Thanks for your help.
