### ISSUE TITLE
Feature request: Add "dark" user interface mode

### ISSUE THREAD

**Issue by CapitalF** [xyzz/acquisition#289]
Please add a dark user interface mode option. Most of PoE's zones are fairly dark and it's jaring to the eyes to go back and forth between a completely white user interface and a mostly-dark one.

I have used Acquisition Plus in the past and really like it's dark mode. I would very pleased it if a similar mode was added to Acquisition.

Thank you for your consideration.

**Comment by livejamie** [comment]
Running this on a second monitor and would love for a dark mode, it's the only bright thing on my screen

**Comment by ericsium** [comment]
This is unlikely to get implemented directly in the program unless someone who is invested in it sends a pull request.  However, the next release should already support OS level dark themes.  See #373.  Windows 10 comes with some high contrast black themes that might work for you.

**Comment by livejamie** [comment]
This is actually implemented nearly perfectly in @Novynn's fork of acquisitionplus: https://github.com/Novynn/acquisitionplus/releases

I don't know what would be involved in getting it in Acquisition 

He's no longer maintaining that repo
