### ISSUE TITLE
Cannot log in acquisition Network error:connection closed

### ISSUE THREAD

**Issue by fljsdbd** [xyzz/acquisition#292]
Hi, i met this problem right now, I cant log in my acquisition. Usually i just remembered the possession id and click log in. Now it said that "Network error: connection closed". So i tried to use the steam account to log in. still didnt work. can you help me solve this problem?

**Comment by Hardell** [comment]
Same thing here.
Sometimes it logs in but nothing works and I get stuff like this:

 WARN 2016-04-02T01:27:21.207 Can't extract selected character name from the page 
 WARN 2016-04-02T01:28:17.550 7 got a non-object response 
 WARN 2016-04-02T01:28:17.551 8 got a non-object response 
 WARN 2016-04-02T01:28:17.551 9 got a non-object response 
 WARN 2016-04-02T01:28:17.551 10 got a non-object response 
 WARN 2016-04-02T01:28:17.551 11 got a non-object response 

This is for 0.5c, I'm gonna update to 0.5e and see if this continues.

**Comment by ericsium** [comment]
The path of exile website itself seems to be having issues right now.  If you're having problems using the website it's likely that the API interfaces are also effected and could cause various issues.  Let me know if it clears up for either of you.

**Comment by ericsium** [comment]
If it doesn't please read troubleshooting [First-Steps](First-Steps) to see if you can resolve your issues from solutions found in previous threads.

**Comment by Hardell** [comment]
You were correct. Once the website started working properly again, the issue disappeared.

**Comment by ericsium** [comment]
Closing, assuming these were related to GGG network issues.
