### ISSUE TITLE
Listing wrong prices on poe.trade

### ISSUE THREAD

**Issue by JeZipoE** [xyzz/acquisition#293]
I've set up Acqusition, by following guides and stuff from youtube. And it have worked perfectly.
But suddenly it has started to list completely wrong itemprices. 

For example an item that I put a buyout on 4ex in Acquisition, shows up on poe.trade for 5c. I have tried to reinstall, reprice, update, everything more than once and nothing helped so far.

I really hope you got some solution on my problem.

Pictures of just one of the buyout issues: 

![123](https://cloud.githubusercontent.com/assets/18227202/14225167/2bfc6d9e-f8b9-11e5-985a-d73e8a3408d9.png)
![456](https://cloud.githubusercontent.com/assets/18227202/14225168/2bfc825c-f8b9-11e5-8c19-e4f82b258821.png)

**Comment by ericsium** [comment]
Can you provide a link to your thread?  What version of aquisition are you currenty using?

First we need to determine if this is an aquisition issue or not.  If it is not priced correctly in your shop and the data does not match up with your pricing in aquisition then it could be an acquisition issue, if it is priced correctly in the shop then it would be a poe.trade or GGG issue (the item ID interface/API is new).

**Comment by ericsium** [comment]
BTW, if you do reinstall and want to try repricing again it's critical to delete your old database.  If it's corrupted uninstalling/reinstalling won't really help:

See [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) on how to do this.

**Comment by JeZipoE** [comment]
https://www.pathofexile.com/forum/view-thread/1638693

There's a link to my thread, as you can see, it's totally messed up.
So, the prices in my acquisition is right, but my thread/poe.trade looks like that ^.

I am using the newest version of acquisition.

**Comment by Gloorf** [comment]
This is not a shop generated by acquisition, it's a procurement thread, are you sure it isn't running too ?

**Comment by ericsium** [comment]
Now it looks correct.

**Comment by JeZipoE** [comment]
Yes it does, but on poe.trade it shows up, as in my first example. Taste of hate for 5c, but in acquisition I have set it to 4ex.
And I'm not using procurement, it's deleted from the pc, so it's not running at the same time

**Comment by JeZipoE** [comment]
Hmm, I followed the guide to delete everything in acquisition. Then I listed those 2 items and they show up correct. But it seems like it goes back to messing around with prices, when acquisition "auto-online" my status.

**Comment by ericsium** [comment]
On poe.trade it's showing up as 4ex, just like in the thread.  That shop thread was using procurement and hadn't been updated since yesterday.  So maybe you didn't have aquistion setup properly to auto-update your shop?  Can you review https://www.youtube.com/watch?v=HeqU9jkWRy0 and make sure you have 'automatically update shop' checked to make sure you pricing and your thread are kept in sync?

http://poe.trade/search/iyonohuakinama

**Comment by JeZipoE** [comment]
Ah ye, hmm, I can see it now. I was just searching for "taste of hate" and for some reason it shows up with a buyout on 5c AND a buyout at 4ex. So the prices are "right" again.

**Comment by ericsium** [comment]
The 5c pricing for taste of hate is coming from your 'other' procurement thread apparenty that seems to quite messed up category wise.  You can find the taste of hate 5c pricing deep in the 'unique' section.

https://www.pathofexile.com/forum/view-thread/1456161

If you're moving to aquisition delete that old thread.

**Comment by JeZipoE** [comment]
Since I can't delete my threads, I deleted all text in my old trading threat, so it's only the new with item's. All though I did this, my taste of hate keeps showing 2 times, and still one of them is for 5c, it's really weird.

**Comment by ericsium** [comment]
It will take some time (not quite sure how long) for poe trade to reindex the thread and see that the 5c version is no longer listed.  To be on the safe side 'bump' the thread or post it it so it goes to the top and should get reindexed faster.

**Comment by JeZipoE** [comment]
Looks like it works again! Really appreciate all that help, thank you!

**Comment by ericsium** [comment]
You're welcome.
