### ISSUE TITLE
I cant edit my prices

### ISSUE THREAD

**Issue by phanton0152** [xyzz/acquisition#294]
I'll just leave this pic here, and u will know whats my problem...

![bug](https://cloud.githubusercontent.com/assets/18247553/14233578/1e7ec2bc-f9a3-11e5-82b0-d054d7e55f5c.jpg)

**Comment by ericsium** [comment]
If you have a 'note' set on that item in game giving it pricing information aquisition will honor that pricing info and prevent you from pricing in aquisition.

Does it have a note set on it in game pricing at 75 exa?

**Comment by phanton0152** [comment]
Yeah, its note on him. Ty bro

**Comment by ericsium** [comment]
No problem, I'll send you the bill (one fishing rod).
