### ISSUE TITLE
acquisiton.exe is not a valid win32 application (WinXP)

### ISSUE THREAD

**Issue by lothraine** [xyzz/acquisition#295]
I haven't been able to run any Acquisition releases since Perandus League Started. They all have the same error (see title). I have been trying a few different things in order to get it to work:
1. Uninstalled, cleared registry, re-downloaded and re-installed it in a "non space" directory (space directory eg: Program Files). I know XP has these kind of problems;
2. Tried to modify the ImagePath using regedit;
3. Uninstalled and reinstalled .netframework (don't know if that was an issue to begin with but i did it anyway);
4. Tried to "Run As..." (of course Administrator...)
Please send help, my Stash is getting full !!! xD
Thanks in advance.
![acquisition](https://cloud.githubusercontent.com/assets/18270256/14260147/c3ef3e2e-fab2-11e5-99c5-9976b40c3f78.JPG)

**Comment by xyzz** [comment]
Yes, windows xp is not supported. I don't know why it worked before, it should not have.
