### ISSUE TITLE
ERROR 2016-04-07T11:11:51.956 Can't even fetch first tab. Failed to update items.

### ISSUE THREAD

**Issue by naiadsmystery** [xyzz/acquisition#299]
I've been repeatedly receiving this error when Acquisition tries to auto-refresh as well as when I initiate a manual refresh. I've tried restarted Acquisition, POE, computer, re-entering my trade and shop URL..nothing helping.
Any ideas what's causing this?
ERROR 2016-04-07T11:11:51.956 Can't even fetch first tab. Failed to update items.

**Comment by ericsium** [comment]
Start here and see if you can identify and fix your issue - Debugging [First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps).

Please respond in the thread if any of those steps resolved the problem.  If they don't we can look further.

**Comment by naiadsmystery** [comment]
I reinstalled Acquisition (I think? It didn't seem to lose any of my settings but I deleted the program file then ran the installer again.) and this thread https://github.com/xyzz/acquisition/issues/254 wasn't very helpful. And I received the same error on start up.

**Comment by ericsium** [comment]
Reinstalling aquisition will not remove possibly corrupt db or authentication information etc...  Make sure you follow the 'clear your aquisition prefs' section of the doc I mentioned.

Also, make sure you use same authentication methods on both aquistion and website and make sure you can log in both places.  Are you using steam or standalone client, do you have both and switch between them?

**Comment by ericsium** [comment]
Also, try different leagues and see if you have the same problem, and change your 'active character' in poe website to another char and try it.

**Comment by naiadsmystery** [comment]
Clearing the acquisition preferences worked. Thanks so much for your help :)
Also to answer your questions, I use the steam client and authenticate both with my steam login.
