### ISSUE TITLE
Error while submitting shop to forums: Field cannot be empty 

### ISSUE THREAD

**Issue by MelvinMenendez** [xyzz/acquisition#307]
How do I fix this. (Error while submitting shop to forums: Field cannot be empty)

**Comment by ericsium** [comment]
Go to 'Shop -> Shop Template'.  You may have inadvertently modified this field.

It should contain the text '[items]' (not in quotes).  Let me know if that fixes the issue.

**Comment by MelvinMenendez** [comment]
Okay no I am getting an error message that says, (Error while submitting shop to forums: Duplicate submission token has expired. Please submit the form again.)

**Comment by MelvinMenendez** [comment]
Okay I fixed it. Thank you!
