### ISSUE TITLE
Auto Online taking me offline

### ISSUE THREAD

**Issue by Jadron** [xyzz/acquisition#310]
Hi, I have the same problem as issue thread #136 however I am a Windows user.

I use steam streaming, windows10 on both pc and laptop.

My poe control link is correct, when acquisition is launched on first auto-update I get a red "offline" in the corner. On further inspection manually operating my poe control link in a browser shows if the auto update in acquisition triggers it actually wipes any remaining time and places me offline.

If I turn autoupdate off, manually update time via poe control in my browser everything works fine.

Any ideas on what I can do? I noticed steam has an alternate .exe name for streaming client.

**Comment by ericsium** [comment]
Aquisition does require the POE client to be running to show you as 'online' and will force you 'offline' if you don't have the .exe running on the same computer the acquisition process is running.

You can review the code here and see the .exe names it tries to detect and confirm whether those are the .exe's that are running for POE or not:

https://github.com/xyzz/acquisition/blob/master/src/autoonline.cpp#L68

**Comment by Jadron** [comment]
Ahh works perfect now! Replaced it with-> streaming_client.exe

Seems obvious, but I am not a coder, much thanks!

**Comment by ericsium** [comment]
BTW, we can't really support streaming_client.exe for auto-online as it appears there would be no way to tell you're streaming POE vs another game.  I'll create an issue to enhance the code to identify this case and warn the user.
