### ISSUE TITLE
 Error while submitting shop to forums: Value is required and can't be empty and cant extract character name errir

### ISSUE THREAD

**Issue by Exninth** [xyzz/acquisition#314]
can i know what happes in here ?
if i leave the item with no price it says " shop thread updated" when i click to update shop thread at forum
 but once i selected the buyout out price.. it will show me the error
please help

**Comment by ericsium** [comment]
Please review [troubleshooting first steps](https://github.com/xyzz/acquisition/wiki/First-Steps) and see if you can resolve your issue.

**Comment by Cruentaferae** [comment]
Lol many pepol say tis issure and all y say it get to first tep and look if it help its not....
