### ISSUE TITLE
Missing Currency type - by using prenium tab sale

### ISSUE THREAD

**Issue by kishikouma** [xyzz/acquisition#317]
WARN 2016-04-28T09:10:03.960 Cannot map string: ' "exa," ' to currency type.  This should not happen - please report. 
 WARN 2016-04-28T09:12:04.218 Cannot map string: ' "exa," ' to currency type.  This should not happen - please report. 
 WARN 2016-04-28T09:14:04.269 Cannot map string: ' "exa," ' to currency type.  This should not happen - please report. 
 WARN 2016-04-28T09:16:04.231 Cannot map string: ' "exa," ' to currency type.  This should not happen - please report. 
 WARN 2016-04-28T09:18:03.763 Cannot map string: ' "exa," ' to currency type.  This should not happen - please report.

**Comment by ericsium** [comment]
You have a comma immediately after 'exa' which is unexpected.  It may be that poe trade will accept this.  Aquisition uses a slighly method to identify currency types - it requires a space currently after specification of currency types.

I'm assuming you manually priced in game and added the comma after 'exa'?

Nevertheless marking as bug, but I'd consider this one fairly low priority for fixing.

**Comment by kishikouma** [comment]
ive no comma after it
http://imgur.com/ZC8Yqni

**Comment by ericsium** [comment]
I'm unable to duplicate, I priced an item at 1 exa ingame and I'm not seeing any errors.  I'll need more context or information to look further.

**Comment by ericsium** [comment]
I've made some changes that should prevent these warnings and ignore non-word characters.  Doesn't really explain where that comma might have came from though.
