### ISSUE TITLE
Program - Acquisition Error-update!

### ISSUE THREAD

**Issue by SevenSinsOfHell** [xyzz/acquisition#321]
"Errors and warnings will be printed here"
"ERROR 2016-05-01T20:03:20.729 Asked to update a shop with no shop ID defined. "

This is what i have everytime the program wants to update the "Shop" / 30min.
1. I have added my Auto online (Control.Poe.Trade)
2. I've have checked so my tab is "public" and that the prices are set as "Exact price"

Now What is it that causes this to be Error all the time?
(Bottom right corner) says im "ONLINE"
NOTE: i have logged into the program with my POE account (not the poe.ID) for "Poe.Trade"

So please help me here... Also i have Enabled in the list all my characters so i can recive the whispers.

![error update acquisition shop id](https://cloud.githubusercontent.com/assets/18729477/14944197/6f2967e4-0fec-11e6-9f27-784705479420.jpg)

**Comment by ericsium** [comment]
You need to create a shop thread at path of exile forumns and enter the thread id in 'shop -> forumn shop thread'.

**Comment by ericsium** [comment]
Closing due to either resolved or inactivity.
