### ISSUE TITLE
ERROR 2016-06-08T20:33:33.824 Error while submitting shop to forums: Duplicate submission protection enabled. You may have submitted this form already. If you haven't then please submit it again. 

### ISSUE THREAD

**Issue by Roentved** [xyzz/acquisition#331]
What can i do?:D clean reinstalled 2 times.

Version 0.5g

**Comment by ericsium** [comment]
Please go through the [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) document and see if you have any luck resolving your problem.

**Comment by Roentved** [comment]
cleared the appdata and it worked. Thanks
