### ISSUE TITLE
Unable to stay online in POE trade

### ISSUE THREAD

**Issue by Scorpse01** [xyzz/acquisition#335]
Hello

I cannot stay online in poe.trade unless I do it manually using the URL given to me by poexyzis.

I have updated the control.poe.trade URL in Acquisition and enabled the auto update. My character is in the ladder. Acquisition reports that I am online.

I have uninstalled Acquisition and reinstalled. It does keep the details though so I am not sure if this needs to be reset.

Do I need to reinstall POE as well?

Sorry for this thread. I have been looking online to try and resolve the issue but i have had no luck fixing it. This problem has only really started a week ago.

**Comment by ericsium** [comment]
As I understand it if you're on the ladder poe.trade uses GGG auto-online API to detect your online status and your control.poe.trade URL is only used as a backup if you're not on the ladder.  So this is strange...

You can check out [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) and see if you have any luck resolving your problem.

For more info on how auto-online works see [Auto-Online](https://github.com/xyzz/acquisition/wiki/Auto-Online).

Reinstalling POE will not do anything.  You can delete acquisition prefs but again as you're on the ladder I'm not sure this is actually an aquisition issue.

**Comment by ericsium** [comment]
You are logged into the game right?  Auto-online does not work if you are not logged into the game.

**Comment by ericsium** [comment]
Got some better information on how this works, please check out [Auto-Online](https://github.com/xyzz/acquisition/wiki/Auto-Online) again.  The Ladder API is very slow to update (can take up to an hour to notice you are online).  When you see green 'online' in acquisition it can take a minute or two until poe.trade processes you as online.  So give it at least five minutes before you check your status.

Let me know if this resolves things.
