### ISSUE TITLE
Select buyout by item not by itemgroup?

### ISSUE THREAD

**Issue by GreatProjects** [xyzz/acquisition#336]
Is it somehow possible to select the buyout for each item individually? For example: If i want to sell a spell gem for 2 alterations, every spell gem of the same kind would also be buyout. Why is that?

**Comment by ericsium** [comment]
Items are currently identified in the tool as a hash of the item's attributes, so it's not possible currently to set different buyouts on items with the same attributes.  This is already described in enhancement request #258.
