### ISSUE TITLE
Adding options to path of exile exe prevents auto-online from working properly

### ISSUE THREAD

**Issue by scrybz** [xyzz/acquisition#339]
I've tried everything in the wiki and in the other threads but i cant get it to show me as online, it only worked for the first hour or so after i installed then stopped.

**Comment by scrybz** [comment]
i pasted the control from poe.trade and enabled auto online, I've tried to re-install acquisition a few times aswell. Everything works, i've managed to list my items and create a shop but the only way for me to be online is manually pressing the 'become online' button on control every 5 mins.

**Comment by ericsium** [comment]
In acquisition does it say 'online' or 'offline'?

Are you using steam streaming client?

Are you actively logged into the game when you are checking online status?

**Comment by scrybz** [comment]
I'm playing through the poe client, it says offline while i'm logged in the game.

**Comment by ericsium** [comment]
Are you on Linux or windows?  What OS?  The auto-online code is fairly simple, it just looks for a process which a certain name:

https://github.com/xyzz/acquisition/blob/master/src/autoonline.cpp#L68

if (s == "PathOfExile.exe" || s == "PathOfExileSteam.exe")

Is your executable name changed, can you confirm whether those processes are running when auto-online is enabled?

**Comment by scrybz** [comment]
Windows 7, im running it as --noasync, i'm guessing thats probably why

**Comment by ericsium** [comment]
Can you try without --noasync to confirm?  I'm guessing you're correct, it's not a regexp so that code is probably not anticipating options were passed.

**Comment by scrybz** [comment]
It's working now. thanks a lot for the help

**Comment by ericsium** [comment]
Was the issue --noasnc and fixed if you removed?  If so I'll mark this as a bug.

**Comment by scrybz** [comment]
yeah, it doesn't work with --noasync

**Comment by xyzz** [comment]
should be fixed now
