### ISSUE TITLE
How do you get the POESESSID?

### ISSUE THREAD

**Issue by GreatProjects** [xyzz/acquisition#345]
Hi developer,

i am wondering how you get the POESESSID from the browser? I can't figure it out reading your code. It would also be interesting which JSON requests you use because none of them is documented at the official website from GGG?
I am looking forward to a reply from you.

Edit: Okay, i found it out myself. For anyone who is interested in it (for Chrome): You have to select the SQLite table in your local application data folder

**Comment by ericsium** [comment]
Regarding the API requests you should be able to figure it out by following these variables and how they are set using QUrl:

https://github.com/xyzz/acquisition/blob/master/src/itemsmanagerworker.cpp#L43
