### ISSUE TITLE
Dont showed me online poetrade 

### ISSUE THREAD

**Issue by armed109106** [xyzz/acquisition#346]
Im online in game , acquisition status have online ! but my items dont have here not online and dont offline sellers ! this all items have in my thread shop : please help me

**Comment by Tomeqf** [comment]
Just open D9 version of PoE and leave it in login menu. It will make acquisiton update the status, and you can play on Dx11 PoE

**Comment by armed109106** [comment]
D9 ?

**Comment by Tomeqf** [comment]
DirecctX 9 version (32 bit), aka the 'good old' version of PoE

**Comment by xyzz** [comment]
Please download the new Acquisition release.
