### ISSUE TITLE
Don't install to program files

### ISSUE THREAD

**Issue by Asday** [xyzz/acquisition#349]
I install all programs to D:\app.  Why can I not specify where to install in the installer?

**Comment by xyzz** [comment]
You can if you install it for the first time. Otherwise, if you are upgrading current installation, it will overwrite the existing files. Uninstall current version and install Acquisition again if you want to change the path.

**Comment by Asday** [comment]
Well there's some manner of bug.  I reinstalled Windows, but kept running Acquisition from the last install, (hence installing it on D:).

It asked me to upgrade, I did, and I wasn't able to select install location, and it installed to program files.
