### ISSUE TITLE
Can't extract selected character name from the page  Troubles 

### ISSUE THREAD

**Issue by YesYesYe** [xyzz/acquisition#356]
Today i open my acquistion and what i see?Hmm /Can't extract selected character name from the page/
Help me pls :)<-:(

<script src="https://gist.github.com/YesYesYe/c97abfde2c0c950affd5c0a4775455a1.js"></script>

**Comment by YesYesYe** [comment]
[https://gist.github.com/YesYesYe/c97abfde2c0c950affd5c0a4775455a1](url)

**Comment by YesYesYe** [comment]
[http://pastebin.com/UwcrpugQ](url) <--- my localappdata log.txt

**Comment by Cruentaferae** [comment]
hi i have same problem 
1. I've checked my login information and it is correct.
2. Thread is updating fine.
3. I'm not showing up online at poe.trade (I have my Control URL set up)
4. The program is fetching my tabs fine.
5. Reinstalled it, but it didn't fix.

**Comment by ericsium** [comment]
Please go through the [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) document and see if you have any luck resolving your problem.

Deleting preferences often fixes strange issues.

For auto online issues please read [Auto-Online](https://github.com/xyzz/acquisition/wiki/Auto-Online).

**Comment by Cruentaferae** [comment]
i do it all a lat of time and its not worcking

**Comment by xyzz** [comment]
This is just a warning, it's harmless.
