### ISSUE TITLE
poe.trade doesn't show me online

### ISSUE THREAD

**Issue by Demonell** [xyzz/acquisition#357]
same like this problem: https://github.com/xyzz/acquisition/issues/315

Acquisition shows me online when poe.trade never shows me online. When i check/uncheck Automatically Refresh Trade Status it shows me: "Online URL is probably invalid." though URL is in right format: http://control.poe.trade/blablabla

I use steam client (not streaming one) and i use Acquisition 0.4 cuz 0.4a shows me: This application failed to start because it could not find or load a Qt platform plugin "windows". And I downloaded it from [here](https://github.com/Novynn/acquisitionplus/releases/tag/0.4a-PLUS) many times. Nothing help. But 0.4 works well besides this Online Problem.

My http://control.poe.trade/blablabla link show me "You are not online. Or maybe you are. Who knows." Using "become online" is working for 5 mins. Then i'm offline again at poe.trade and still online at Acquisition.

**Comment by Demonell** [comment]
Tried Acquisition 0.5g, same problem. Shows me online in program but offline on poe.trade

**Comment by ericsium** [comment]
Can you re-request your online URL from in-game and paste in exactly what you get and try it?  Mine looks like  http://control.poe.xyz.is/blahblah.

Also check out this page which might help:
https://github.com/xyzz/acquisition/wiki/Auto-Online

**Comment by Demonell** [comment]
Oh wow, changed control.poe.trade to control.poe.xyz.is and it works! Well maybe something just was fixed and control.poe.trade works too but i'm too scary to change anything xD

**Comment by Anhelo** [comment]
Hello Ericsium!

I have same problame with Acquisition! 

The program said, i was online, but in poe.trade i can found my item in offline members, and i see bottom of my item: Verify Profile (instead of IGN: Myingamename Whisper)

Thx mate ! :)
