### ISSUE TITLE
Delete price of items when close Adquisition

### ISSUE THREAD

**Issue by KaciuZ** [xyzz/acquisition#358]
Good afternoon, I have a problem with the acquisition, is that every time I close the program prices of the items are deleted.
uninstall it, I went back to install .. When I put prices works well, but when you close the program deletes prices ..

**Comment by ericsium** [comment]
Please go through the [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) document and see if you have any luck resolving your problem.

You probably have a corrupt DB and need to clear your preferences.

**Comment by xyzz** [comment]
no reply - closing
