### ISSUE TITLE
Same problame with #357

### ISSUE THREAD

**Issue by Anhelo** [xyzz/acquisition#359]
Hello Ericsium!

I have same problame with Acquisition!

The program said, i was online, but in poe.trade i can found my item in offline members, and i see bottom of my item: Verify Profile (instead of IGN: Myingamename Whisper)

And i change http://control.poe.trade/blablabla to http://control.poe.xyz.is/blahblah but it havent worked yet :(

Example: First hit for 5 Orb of Alternation   http://poe.trade/search/ukoyakorihokuk

Thx mate ! :)

**Comment by Anhelo** [comment]
Example: First hit for 5 Orb of Alternation:

http://poe.trade/search/ukoyakorihokuk

**Comment by ericsium** [comment]
Please go through the [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) document and see if you have any luck resolving your problem.

For auto online issues please read [Auto-Online](https://github.com/xyzz/acquisition/wiki/Auto-Online).

I think it can take some time (I think maybe five minutes) before poe.trade recognizes you as online from the time that Acquisition indicates you are online.

**Comment by Cruentaferae** [comment]
i have same eror and on poe trade i offline and ont have ing (verify prifile) ant any option to set me online dont worck and i cant set anatyng on carensy shop acquzition say i onlin on last 2 hours and it wrong... also have Can't extract selected character name from the page

**Comment by Cruentaferae** [comment]
and i can connect to boe trade but cant connrct to poe xyz

**Comment by ericsium** [comment]
Does your control URL look like this?

http://control.poe.xyz.is/...

Or is it using the old format?  If you're characters name uses international(non-english) characters there may be an issue as the parsing logic might be getting confused by the characters.  Try creating a char with an english name, go to path of exile website and 'select' that character to make it 'active' then see if it works.

**Comment by Cruentaferae** [comment]
i switck char control poe xyz say i online but i not online in curesy shop i set best ratio for futo to ex and i not in search

**Comment by Cruentaferae** [comment]
i tinck xyz dont care if ane one dont worck good job!

**Comment by ericsium** [comment]
If nothing on this page resolves the issue I don't have any other great ideas:

https://github.com/xyzz/acquisition/wiki/Auto-Online

If this is very important to you the easiest way to make sure you are shown online is to buy one premium tab and set it to 'public'.

**Comment by xyzz** [comment]
#346
