### ISSUE TITLE
 launcher not a 32bits valid file

### ISSUE THREAD

**Issue by aengis** [xyzz/acquisition#360]
it installs correctly, but once i try to launch it, there is an error saying that it is not a 32bit valid file.

win xp sp3 32b.

**Comment by xyzz** [comment]
Windows xp is not supported by Acquisition

**Comment by aengis** [comment]
then im pretty much .. fcked,
 right? 

going to try launching it in a VM with win7 and i'll tell u how that goes.

**Comment by bsun0000** [comment]
Meh.. why you drop the support for entire app, if you can simple create a non-steam version for a XP users? Without WebKit module, everything else works and compiles fine. For me, it took just 10 minutes to remove steamlogin-related code and compile this program..
