### ISSUE TITLE
new patch problem, aquisition sets you offline, cant detect the new x64.exe 

### ISSUE THREAD

**Issue by kick-darkangel** [xyzz/acquisition#362]
With the new patch and the new x64 game exe file aquisition will set you as offline.

**Comment by ericsium** [comment]
I've submitted a pull request that should fix this for when xyz gets time to do an official update.

**Comment by Tomeqf** [comment]
While waiting for devs to update acquisition to detect PathofExile_64x.exe task (Dx11 version), just open DX9 version of PoE and leave it in login menu, mute, minimize, and go play on Dx11 version. Leaving D9 version in login menu is enough for acquisition to update status, as it simply searches for Pathofexile.exe task being run.

**Comment by xyzz** [comment]
Fixed by #363 release incoming
