### ISSUE TITLE
Item's not appearing in thread (copy to clipboard coming up empty too)

### ISSUE THREAD

**Issue by DrewCD** [xyzz/acquisition#369]
Hello,

My shop thread is 1782274, so https://www.pathofexile.com/forum/view-thread/1782274 and my tabs are listed as '~b/o x chaos' (the items within inherit the prices) however whenever I update the thread it updates as 'Empty'. This also means PoE trade isn't finding anything, as expected. This is what it looks like:

![capture](https://cloud.githubusercontent.com/assets/24397603/20903147/2bac3b00-bb08-11e6-8fcb-eb25352b0e7e.PNG)

![capture2](https://cloud.githubusercontent.com/assets/24397603/20903182/4dbd0404-bb08-11e6-898d-3ba187763816.PNG)

I am also using the correct account/character and no error messages appear while updating shop.

Any help would be appreciated, I've looked around extensively and still can't seem to find a solution.

**Comment by DrewCD** [comment]
The issue was that that naming the tabs ~buyout x chaos does not work, so I manually set them

**Comment by ericsium** [comment]
See:

https://github.com/xyzz/acquisition/wiki/Pricing-Integration

To learn more about in-game vs acquisition pricing.
