### ISSUE TITLE
Invisible text on OS theme with black background

### ISSUE THREAD

**Issue by cryham** [xyzz/acquisition#370]
So, my Windows7 theme has black background (I use that for over 10years)
and I see the program like so:
http://imgur.com/YcSkkcm
You are setting system color for window background, but use custom black text for text, which is now invisible. To fix this use system color for text too.
This happens for normal items (e.g. maps, divination cards, etc., in 1st column) and all text in later columns too (price, etc.).
It's the main reason I'm not using this program, and was probably in all previous versions too.
You can get my theme file from my website https://cryham.tuxfamily.org/themes

**Comment by ericsium** [comment]
I'm in vacation until Saturday but can but can look into fixing this when I get back.

**Comment by ericsium** [comment]
This is fixed on a branch and should provide support for themes with black backgrounds.  It is tested with the built-in windows 10 high contrast black theme.  This fix should be available with the next acquisition release (could be awhile as xyz needs to do this and this small patch might not warrent an immediate release).
