### ISSUE TITLE
Installer wont close after finishing installation

### ISSUE THREAD

**Issue by haelmut** [xyzz/acquisition#374]
Installing latest acquisition 0.5h, it works normally but after finishing setup processes does not close and works forever. If i force end them system wipe program.

I have 64bit win7 and didn't update anything for years.

Thanks in advance.

![ss 2016-12-14 at 03 29 26](https://cloud.githubusercontent.com/assets/24567907/21183783/329841f0-c212-11e6-9133-66e41aa2a38e.jpg)
![ss 2016-12-14 at 03 27 37](https://cloud.githubusercontent.com/assets/24567907/21183786/367dbd18-c212-11e6-9bb0-578ce0d47819.png)
![ss 2016-12-14 at 03 28 26](https://cloud.githubusercontent.com/assets/24567907/21183789/3935765e-c212-11e6-8d02-54452a7bf7d8.png)

**Comment by ericsium** [comment]
Have you tried rebooting and reinstalling?  Are you sure you're not missing a dialog box, it looks from the pic that it's still open. What's it displaying?

**Comment by haelmut** [comment]
Tried to reboot and reinstall. If i press on setup button from pic1 it wont take any effect except button pressing effect but nothing pop up.

**Comment by haelmut** [comment]
I solved the problem, the Comodo Cloud Antivirus was putting installer in sandbox mode. It quietly installed itself with Comodo Dragon update and i forgot about it.
