### ISSUE TITLE
Acquisition forgets all my prices

### ISSUE THREAD

**Issue by alazlamdurai** [xyzz/acquisition#378]
Acquisition occasionally randomly forgets all my listed prices.  It is almost as if I took everything out and put it back in... How to restore????  This is really frustrating having to reprice entire tabs!

**Comment by alazlamdurai** [comment]
If there is no way to restore, can someone please add the ability to backup prices?

**Comment by xyzz** [comment]
The prices can be lost when itemhash changes, this should be resolved when #258 is implemented. If you take an item out of your stash and then put it back in the price will not be lost.

You can back up your `%localappdata\acquisition\data` directory, but this won't help.
