### ISSUE TITLE
Acquisition 0.5i release

### ISSUE THREAD

**Issue by ericsium** [xyzz/acquisition#391]
Any other issues that need to be taken care of before a 0.5i release?  I haven't personally done much testing as I haven't been able to play in awhile.  But opened in new league and didn't see any obvious issues with latest code.

**Comment by xyzz** [comment]
I can make a release after #392 and #393 are fixed, not sure what other issues are here, I'm not playing myself (sorry for not replying for so long - have been busy w/ stuff).

**Comment by ericsium** [comment]
Sure, no problem.  I'll fix #393 and also maybe the item display rectangle for quad tabs.

**Comment by ericsium** [comment]
0.6 has been released.
