### ISSUE TITLE
[0.5h] Item thumbnails are all bugged for quad tabs

### ISSUE THREAD

**Issue by noraj1337** [xyzz/acquisition#392]
Item thumbnails are all bugged since the new Legacy League, see the following screenshots : 

![](http://i.imgur.com/TCqzxBN.png)

![](http://i.imgur.com/1CLQz4P.png)

![](http://i.imgur.com/mJYLaTM.png)

**Comment by ericsium** [comment]
Can confirm this is a bug and that that icons for thumbnails are shown to be small from quad tabs.  

Regarding part of the tooltip window being cut off - you can resize the frames by dragging between tooltip and central item frame.  Normally best to fullscreen and move to your liking - unfortunately couldn't get the auto-sizing to work reliably.
