### ISSUE TITLE
Multiselect treeview rows

### ISSUE THREAD

**Issue by pajlada** [xyzz/acquisition#40]
Add the ability to select multiple tabs at once, or multiple items at once.
This would give users the ability to change buyout on multiple tabs/items at once.
Would tabs and items be handled separately, or could they be mixed together in a single multiselection.
When the multiselection is active, the right info-box would serve no purpose and should be disabled, or show some information about the current selection.

Multiselection would be achieved with CTRL/SHIFT+clicking multiple rows.

**Comment by ericsium** [comment]
Was resolved with #230
