### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Hexor6T** [xyzz/acquisition#402]
Aren't all stash tabs supposed to be checked? The tabs where I have items with buyouts have a square instead of being checked and I'm pretty sure there has to be an issue because i haven't had offers in the past days even when I set valuable gear to ludicrous low prices (to test it out).

**Comment by ericsium** [comment]
Find more details about tab checked state on the [Pricing Integration](https://github.com/xyzz/acquisition/wiki/Pricing-Integration) wiki page.

Setting prices don't do anything it you don't have a forum thread set up and are either manually or automatically updating the shop thread through acquisition.  For setup basics see [this video](https://www.youtube.com/watch?v=HeqU9jkWRy0).
