### ISSUE TITLE
poe.trade doesnt see my items

### ISSUE THREAD

**Issue by joyowoci** [xyzz/acquisition#403]
I dont have premium tabs, using acquisition 0.6a, non-steam version ( I have 2 clients of poe installed - steam and non-steam. I play always non-steam client )

I did every step in your guide of solving problems and followed it's yoji's youtube guide.  My system has direct x 11 win 7 64 bit . Ingame settings - direct x 9 ( maybe different direct x causes my problem idk, but when I set directx 11 ingame I have cursor monitor resolution problems ) 

some from my log

INFO 2017-03-20T15:56:17.265 "Shop threads updated" 
 INFO 2017-03-20T15:57:15.656 "Received 5 tabs [0 from cache]"

**Comment by ericsium** [comment]
If you're items are shown in your shop thread it's not an acquisition issue.  Can you link your shop thread?  It's not unexpected for it to take around 5 minutes before poe.trade sees your thread updates.

**Comment by joyowoci** [comment]
https://www.pathofexile.com/forum/view-thread/1864814

**Comment by ericsium** [comment]
Yeah, I don't seem to be able to see your items either via search using thread ID or your username so there does seem to be an issue with forum indexing right now.  This is not an acquisition issue though so closing this.  For poe.trade related support and to file issues post on the forum thread: https://www.pathofexile.com/forum/view-thread/109153/
