### ISSUE TITLE
Poe.Trade don't see my listings

### ISSUE THREAD

**Issue by WearMeLikeaGloves** [xyzz/acquisition#410]
I created forum thread on legacy shop, copied numbers of thread, put it into acquisition, wrote poe.xyzis, recieved my link, put this link into acquisition and when i price my item and update my forum thread i see it in the thread but  it doesn't list on poe.trade (online status is green in acquisition), is this problem have something to do with level of char, that i list items from? Cos this is the only guess i have.

**Comment by xyzz** [comment]
This is not an acquisition issue, read first post here: https://www.pathofexile.com/forum/view-thread/109153/page/1#p1089989 and report issues with poe.trade in that topic.
