### ISSUE TITLE
upload to imgur????

### ISSUE THREAD

**Issue by conetopia** [xyzz/acquisition#415]
how does this work? is there a way to have acquisition login to my imgur account?
its not uploading any pictures, and i don't see a config file or anything.

**Comment by ericsium** [comment]
Click on the 'event' log for a message indicating what happened after you click the button.  Will look something like this:

INFO 2017-07-03T22:43:03.917 Image successfully uploaded, the URL is http://i.imgur.com/eOjQlAG.png It also was copied to your clipboard.
