### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mastermind1234** [xyzz/acquisition#416]
Can't update shop -- cannot extract CSRF token from the page.
Reinstalled aquisition
Made new shop thread
Relogged all accounts

**Comment by ericsium** [comment]
Please go through the [Troubleshooting First Steps](https://github.com/xyzz/acquisition/wiki/First-Steps) document and see if you have any luck resolving your problem.

**Comment by mastermind1234** [comment]
Ive done everything in the resolution steps twice now.

**Comment by mastermind1234** [comment]
Fixed.. dummy error. Pasted the whole URL for shop thread ... my bad.
