### ISSUE TITLE
Please consider moving stored info to "my documents"

### ISSUE THREAD

**Issue by IceLancerSR** [xyzz/acquisition#424]
Please consider moving stored info to "my documents"

My documents folder is easily online stored and synced on other devices/PC-s.
I find my self moving a lot and using different PC-s this would greatly fix the problem for many i reckon.

Thanks!

**Comment by TravisEvashkevich** [comment]
Wouldn't this be addressed by


> Command line arguments
> 
> --data-dir <path>: set the path where Acquisition should save its data. By default it's %localappdata%\acquisition on Windows and ~/.local/share/acquisition on Linux.

From the Readme...

**Comment by IceLancerSR** [comment]
Is it too complex to make in app config to change that?

**Comment by ericsium** [comment]
Changing defaults is generally a bad thing as it would break existing users.  Writing migration code is not something any existing contributor is going to want to spend their time doing.  Since there is a reasonable workaround I'm going to close this.
