### ISSUE TITLE
Crash when loading Abyss league tabs

### ISSUE THREAD

**Issue by splitsticks** [xyzz/acquisition#432]
All other leagues load properly, except for Abyss.  Abyss HC does not crash however I do not have a character in Abyss HC.

**Comment by splitsticks** [comment]
Apparently it is the Abyss league specific items that crash Acquisition.  Wearing an abyss league item causes the program to crash immediately upon retrieving items, whereas putting the abyss league item in the last stash tab allows all other tabs to load until the abyss league item is found, upon which the program crashes.

Acquisition does not work in abyss league due to neglect, until the author updates the program.

**Comment by xyzz** [comment]
Please try the following build and let me know if it fixes the issue https://d.xyz.is/acquisition_setup_0.6a-issue-432.exe

**Comment by Lentor123** [comment]
tried the build, it did not fix the issue

**Comment by xyzz** [comment]
Please try the following build: https://d.xyz.is/acquisition_setup_0.6a-issue-432-2.exe

**Comment by xyzz** [comment]
OK, I confirmed that it works and released 0.7 with the patch applied.

**Comment by splitsticks** [comment]
Wow I'm sorry I thought the program was neglected, you crushed those bugs instantly.
