### ISSUE TITLE
handle new map stash tab

### ISSUE THREAD

**Issue by noraj** [xyzz/acquisition#441]
acquisition need to handle the new map stash tab

https://www.pathofexile.com/forum/view-thread/2043782

**Comment by inspire22** [comment]
Any luck with this?

**Comment by xyzz** [comment]
No, we can't do anything about it - GGG's api doesn't return map stash tabs (e.g. check on PoE website, you don't see these tabs at all).

**Comment by zombodotcom** [comment]
https://pathofexile.gamepedia.com/Public_stash_tab_API

**Comment by noraj** [comment]
And also https://www.reddit.com/r/pathofexiledev/comments/48i4s1/information_on_the_new_stash_tab_api/

xyzz Can you reopen please ?

**Comment by damoochie** [comment]
Would love for map tab searching to be possible. I'm hunting Aboxoth so I need to find my maps with beyond mod.
Thanks.
