### ISSUE TITLE
After todays PoE 3.3.0 update Acquisition can't refresh my tabs and send the shop to forum anymore.

### ISSUE THREAD

**Issue by rizzini** [xyzz/acquisition#460]
Hey, guys.

After todays PoE update my Acquisition can't refresh my tabs and send the shop to forum anymore. It is online, tho...

All my friends that uses Acquisition are having the same issue. 

Log:
> Errors and warnings will be printed here
>  INFO 2018-05-24T22:32:46.412 "Received 6 tabs [0 from cache]" 
> ERROR 2018-05-24T22:32:47.185 Error while submitting shop to forums: Security token has expired. Please submit the form again. 

I tried to relogin via Steam and copy the content of POESESSID coockie directly from browser. The issue remains.

**Comment by ericsium** [comment]
You need to login via a regular browser and accept new agreement.  Once you do that using POESESSID worked fine for me.  I tried logging in through steam in acquision and that worked fine as well.  login/password however doesn't seem to work.

**Comment by xyzz** [comment]
They've changed csrf token for forum threads from 32 characters to 128, I'll try to push a new build tomorrow or so.
