### ISSUE TITLE
Error while submitting shop to forums: Security token has expired. Please submit the form again. 

### ISSUE THREAD

**Issue by newguy50** [xyzz/acquisition#461]
Error while submitting shop to forums: Security token has expired. Please submit the form again.  Got this error ever since new patch today, don't know why. Uninstalled and reinstalled and nothing works.

**Comment by popol777** [comment]
Same here

**Comment by PrOm3th3u5** [comment]
same here "Security token has expired. Please submit the form again."

**Comment by xyzz** [comment]
#460
