### ISSUE TITLE
Elemental Damage with attack skills, does not exist as mod

### ISSUE THREAD

**Issue by IceLancerSR** [xyzz/acquisition#466]
This is second broken search function for me.. its now preventing me from using acquisition at all. Can u fix this?

**Comment by DaneelTrevize** [comment]
I suspect the issue is in the string list starting [here](https://github.com/xyzz/acquisition/blob/master/src/modlist.cpp#L39)

As per #465 , Crit Multi, Weapon Ele Damage, and also Elreon's - Mana cost of skills don't currently correctly match for items.

For Elreon's mod, the corrected text from an item's explicitMods property is "-# to Total Mana Cost of Skills", Total is missing.

"+#% to Global Critical Strike Multiplier" seems to be missing the + since the rework.  
"#% increased Elemental Damage with Attack Skills" is the new name for W.E.D.

**Comment by DaneelTrevize** [comment]
Can confirm suspicions, I got QtCreator+MinGW working, and correcting the strings in modlist.cpp fixes the filter & results.

https://i.imgur.com/qiJ5UGY.png

**Comment by ericsium** [comment]
There are a number of these that need cleanup, if you're spending time on this it would be very helpful if you could clean up anything else in this area (I think there are a few other open issues) and send a pull request.

**Comment by DaneelTrevize** [comment]
PR submitted, #489  (not used to GitHub).
Should fix this issue, as well as #465 and part of #456 

I have also created changes for Chaos Damage & DPS columns, correcting the total DPS column, and am looking into adding a dedicated Offencse field for Chaos DPS, but I'm not sure how this should be proposed to this project. Just raise a new enhancement issue & PR?

**Comment by ericsium** [comment]
Thanks - normally you'd sync up the the head on your fork and branches before submitting a pull request and squash related changes into a single commit.  I'm not a git expert either so not sure whether this is a big deal or not.  xyzz can confirm.

It's a good idea to keep pull requests targeted to specific features which it seems like you're already doing.  And yes, raising an enhancement request which describes the indented feature you are proposing to implement is a good idea as it can be used to possibly provide feedback before you spend a lot of legwork on implementation.

A few other tips when you're making changes which will increase the likelihood of a pull being accepted:

  1. Think hard about minimizing the number of changes/files you make to the code.  The cleaner it is the more likely it will be accepted.
  2. This project is fairly inactive currently so don't feel too put off if it takes awhile to get changes accepted.  Generally xyzz will do a new release once there are a number of new changes in the mainline vs a new release for every change.
  3. Hopefully you can gracefully accept coding feedback and be willing to make adjustments to get your pulls accepted.  If it's hard to understand you're code or it looks like a bug farm it's less likely that a reviewer will be motivated to deal with the pull request.
  4. Learn how to squash changes on a branch before submitting pull requests.  For example if you have 10 commits on a branch and they are all related to one change you can squash them all together.  It keeps the mainline cleaner.
 5. Extra points if you study up on modern C++/boost etc... and use existing algorithms and techniques to make your code simpler.  A lot of times google searching will lead you to easy algorithms for doing things.

**Comment by ericsium** [comment]
Other than possibly cleaning up the pull request these changes look fine to me.

**Comment by DaneelTrevize** [comment]
Yeah that just made a damned mess. Followed the instructions, [ended up with duplicated changes](
![image](https://user-images.githubusercontent.com/20874909/47615301-05689880-daa5-11e8-9b71-f7cc1e1c64d7.png)
). Probably going to nuke this fork repo and start again at this rate.

**Comment by DaneelTrevize** [comment]
Ok, new cleaner repo and PR #493
