### ISSUE TITLE
Can We add the new Map Stash Tab?

### ISSUE THREAD

**Issue by zombodotcom** [xyzz/acquisition#470]
https://pathofexile.gamepedia.com/Public_stash_tab_API

![image](https://user-images.githubusercontent.com/13477955/41546452-e5487a7a-72da-11e8-864b-6c5877fb4927.png)

Map Stash tab is up there

**Comment by xyzz** [comment]
It's in the public stash api, but not in the inventory api (you can't see it if you click your portrait on the site).

**Comment by zombodotcom** [comment]
word, thanks, sorry about that
