### ISSUE TITLE
Inconsistent search results/finding items that don't seem to exist

### ISSUE THREAD

**Issue by Ajacmac** [xyzz/acquisition#475]
I did a search for lycosidae in a specific league, being pretty certain I had a few and had just discovered they were somewhat valuable, and acquisition finds 2 of them. I click on one to examine it and either at that moment or at some other point afterwards without me realizing the two items vanished from the search results. Subsequent searches don't find any copies of lycosidae, and searching my stash tabs and characters in standard doesn't turn them up.

I made sure in later searches that I waited for all tabs to load.

What's probably going on?

**Comment by xyzz** [comment]
Before your tabs are loaded, Acquisition searches the old cached copy. Once they are fully reloaded, the results can change.

**Comment by Ajacmac** [comment]
I didn't do anything with the lycosidae, and I only own one or more copies in one league so it isn't possible that I switched from some kind of cache in a different league/same league before selling the shield/s. Is there a reason why it would show up initially if it doesn't seem to exist?
