### ISSUE TITLE
Problem with getting stash data

### ISSUE THREAD

**Issue by sugarjackson** [xyzz/acquisition#477]
This is the error message I am getting, every minute or so another error gets added: 
'Errors and warnings will be printed here

 WARN 2018-08-08T22:27:21.090 18 got 'error' instead of stash tab contents:  {"code":1,"message":"Resource not found"} 
 WARN 2018-08-08T22:28:22.374 32 got 'error' instead of stash tab contents:  {"code":1,"message":"Resource not found"} 
 WARN 2018-08-08T22:29:22.637 33 got 'error' instead of stash tab contents:  {"code":1,"message":"Resource not found"} '

I've done all the necessary steps to set it up, it works fine on incursion league but i get this error on standard. Does anybody know how to fix this? 

Thank you in advance

**Comment by sugarjackson** [comment]
Fixed it by renaming a character that was flagged for rename.

**Comment by simonkowalski** [comment]
I have the same issue - I have renamed a character, but it does not help...
