### ISSUE TITLE
Problem with Poe.trade.

### ISSUE THREAD

**Issue by OpacareAngelus** [xyzz/acquisition#482]
I created a new account. On the old account the program worked, but on the new account, lots do not fall on http://poe.trade. I tried all the solutions found in the guides - nothing helps. My goods simply hang on the forum, but do not fall into http://poe.trade.

**Comment by xyzz** [comment]
Please report any problems with poe.trade to the following support thread: https://www.pathofexile.com/forum/view-thread/109153/page/1
