### ISSUE TITLE
Shown online in other leagues

### ISSUE THREAD

**Issue by Skrzymir** [xyzz/acquisition#484]
Thanks for closing https://github.com/xyzz/acquisition/issues/483 without giving a proper answer and then ignoring me.

**Comment by Skrzymir** [comment]
Mate, if it is really the case that we're always shown online on all characters if we don't have premium stash stabs then:
1) I somehow overcame this and it wasn't the case for me. I 100% wasn't shown online on other characters. Was that a glitch? I don't know. But it was working, I guarantee you. I've played several hours without anyone messaging me and now I'm getting at least a few offers per hour from Standard when I'm logged into Delve.   
2) Why is the option to disable online status for other leagues in the control link if it can't even serve any purpose?  
3) Is there even a way to TEMPORARILY unlist my prices? Changing to [Ignore] removes the pricing permanently, so I'm forced to either play with all the items priced or to remove them entirely... Huge limitation. You need to program in a very simple bit of code that would simply temporarily unlist the items but maintain the pricing within the program. Then there would be no issues like mine.

**Comment by Skrzymir** [comment]
Basically add a [Private] pricing function to Acquisition, so that it is still able to remember the pricing, but doesn't list the items.

**Comment by xyzz** [comment]
You can temporarily delist your items by manually editing your shop forum thread and deleting its contents.

**Comment by Skrzymir** [comment]
I deleted all the items from the forum thread 17 minutes ago, but they are all still listed on poe.trade.  What gives?

**Comment by xyzz** [comment]
You should bump your forum thread for it to be refreshed. If you have any more poe.trade-related questions, please see https://www.pathofexile.com/forum/view-thread/109153/

**Comment by Skrzymir** [comment]
It finally unlisted them.
I should have thought about this, but since I've been using Acquisition I kinda just forgot that it relies on forum threads (other than premium tabs).  
 
Thanks, that helps.
