### ISSUE TITLE
All my prices reset

### ISSUE THREAD

**Issue by klupper** [xyzz/acquisition#486]
I've been using it for two years now.I am completly fucked.is there any log or anyway to roll back?
My rares and my uniques got no more prices to be exact.I have no ideea when it happened but I am guesing in the last 2 days max.

**Comment by Francis95Santos** [comment]
Hello, I have the same problem. My shop thread on the forums still has all my items priced but I cannot refresh and update it, otherwise all my listings will disappear.

The while problem starter today/yesterday after GGG released patch 3.4.3e.

**Comment by xyzz** [comment]
I'm looking into this.

**Comment by xyzz** [comment]
Please try this new build and let me know if it fixes the issue for you.

Before you install and run it, make sure to make a backup of your `%localappdata%/acquisition` directory.

If the issue persists, zip up your `%localappdata%/acquisition/data` directory (the backed up version) and send it to support@poe.trade. Additionally, include a link to your forum shop thread, and a name of one item that should be priced but is not.

https://d.xyz.is/acquisition_setup_0.7b-issue-486.exe

**Comment by Francis95Santos** [comment]
Problem is not solved with the new build, my old prices still don't show up on Acquisition.

I sent the email with my backed up data.

**Comment by xyzz** [comment]
Okay, try the following build: https://d.xyz.is/acquisition_setup_0.7b-issue-486-2.exe
