### ISSUE TITLE
Leagues API returned malformation data operation canceled

### ISSUE THREAD

**Issue by finalkenpachi** [xyzz/acquisition#505]
Hello

today my acquisition stopped refleshing. Then i try to reopen but when i click the login button i got this message. Few second later this massage changed to: "Network error connection timeout"

Anyway to fix this? Thanks

**Comment by finalkenpachi** [comment]
Looks like site is down atm. Maybe i get this error because of that.

**Comment by TreantBG** [comment]
It happened today as well
