### ISSUE TITLE
Unable to select League 

### ISSUE THREAD

**Issue by AsdAsdAsd001** [xyzz/acquisition#506]
I am unable to select a league, the box is grey. (Attached screenshot below)
![screenshot 2](https://user-images.githubusercontent.com/45220138/48817010-6ff8b580-ed7f-11e8-8a88-056093fc3af7.png)

Edit: It worked yesterday but after poe.trade went down for a few hours I couldn't load acquisition back up.

**Comment by Sumtin123** [comment]
I Am Having The Same Issue, I Have Tried Uninstalling And Reinstalling And I Have Also Tried To Clear The AppData as per A Post I Found from two years ago with the same problem. best knowledge I can find is that it is an issue on GGG Side.

**Comment by AsdAsdAsd001** [comment]
Fixed the issue but had to delete the acquisition file at %localappdata%\acquisition so rip all my pricings
