### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Wraeclaster** [xyzz/acquisition#510]
Hi,

So I'm unable to log in with any method, POSESSID or email. I don't have the game on Steam.

The error I get is:

Network error: Error transferring https://www.pathofexile.com - server replied: Forbidden.

I've changed my account password to see if that helped, but still can't log in.

I tried using a different browser, (Opera instead of Chrome) to get a new session ID, logging out of Chrome, and switching soley to Opera, but still the same error.

Any ideas what else I could try?

EDIT: I uninstalled Acquisition, manually removed all leftover files, restarted, reinstalled, same problem.

Thanks.

**Comment by HauntedPleb** [comment]
Having a very similar issue.

I am also unable to utilize any of the login methods. I do have the game linked up with Steam

The error I get is:

Network error: Error transferring https://www.pathofexile.com - server replied: service temporarily unavailable

Tried similar fixes, would love some help ^^

**Comment by ElNastyBardo** [comment]
Same ( Network error: Error transferring https://www.pathofexile.com/login - server replied: service temporarily unavailable ) problem here.

**Comment by finalkenpachi** [comment]
same started 3-4 hours ago.

**Comment by mega2k0** [comment]
same here "temporary unavailable"

**Comment by Iblooddrunk** [comment]
Some problem to. Fix plz.

**Comment by xyzz** [comment]
It seems that GGG has put login button under a more aggressive cloudflare to stop DDoS attack. As a side result, this breaks tools like Acquisition (which don't behave like a normal browser would). Unfortunately there's no easy solution to that on our side. I might look into this more next week if they don't disable CF by then.

**Comment by Iblooddrunk** [comment]
xyzz
Thanks for the answer. We will wait.

**Comment by finalkenpachi** [comment]
ggg joking to us

**Comment by mega2k0** [comment]
we r fu*ked

**Comment by alfanjorfresco** [comment]
next week? :(

**Comment by Wraeclaster** [comment]
> xyzz
> Thanks for the answer. We will wait.

Thanks for the reply, xyzz. Fingers crossed.

**Comment by xyzz** [comment]
Okay, it turns out it's simpler to resolve than I initially thought (although you'll have to log in through steam or manual Session ID entry) so I'll try to push a new build today.

**Comment by alfanjorfresco** [comment]
> Okay, it turns out it's simpler to resolve than I initially thought (although you'll have to log in through steam or manual Session ID entry) so I'll try to push a new build today.

ty xyzz ;)

**Comment by xyzz** [comment]
Fixed in 326668b28f6e81b8340d527c9d604509e5e75185

**Comment by Iblooddrunk** [comment]
xyzz
Thanx very much!!!
