### ISSUE TITLE
Option to only download specific tabs

### ISSUE THREAD

**Issue by xyzz** [xyzz/acquisition#53]

**Comment by WhiteSp1rit** [comment]
This is an absolutely required feature - program is borderline unusable without it if a player has a large number of tabs.
There should be:
a) Option to reload one or multiple selected tabs on demand
b) Option to select which tabs are reloaded automatically. People need autoreload mostly for shops, they don't need to reload 100+ tabs every time for no reason whatsoever.

**Comment by ericsium** [comment]
Resolved with #230
