### ISSUE TITLE
Can't login since today 0.8b

### ISSUE THREAD

**Issue by klupper** [xyzz/acquisition#535]
I had no issues until now.Closed my pc went out for a couple of hours and I can't login anymore with session id  or email/password. says invalid password or expired session id.Did not touch anything and I only have a shop on standard.the same shop i have for years now.

**Comment by master2g** [comment]
Just got this today as well.  I'm gonna try reinstalling and see if that helps.

**Comment by furer** [comment]
"Failed to log in (invalid password of expired session ID? try re-logging with email/password pair or via steam" this message today.

**Comment by master2g** [comment]
Yeah reinstalling fixed it for me.  Just redownload and install it again.  All of your stuff should be exactly like it was guys.

**Comment by xyzz** [comment]
The GGG seems to have expired all the sessions, you will need to relogin on the website and grab the new session id.
