### ISSUE TITLE
Spolier tag when pushed to forum

### ISSUE THREAD

**Issue by Neekapoop** [xyzz/acquisition#536]

**Comment by Neekapoop** [comment]
I just installed aquistion, but when it moves items to my forum thread, everything is under a spoiler tag.
How do I remove that?
Thanks!

**Comment by xyzz** [comment]
It is not possible.

**Comment by Neekapoop** [comment]
> 
> 
> It is not possible.

so this is normal? if it isn't, what am I doing wrong?

**Comment by xyzz** [comment]
Yes, it's supposed to put everything into one big spoiler tag. You can add some text around it by editing the shop template, but there is no way to get rid of the spoiler tag.

**Comment by Neekapoop** [comment]
ok, good to know. thanks! I also have not seen any of the items on poe.trade. Is there a normal time delay, as I put these up two days ago.  Thanks for all your help!

**Comment by xyzz** [comment]
For poe.trade support, use the following forum thread: https://www.pathofexile.com/forum/view-thread/109153/page/1
