### ISSUE TITLE
doesn't handle the new unique tab

### ISSUE THREAD

**Issue by qwak-adikt** [xyzz/acquisition#538]
Results are not being included from the new unique tab.

**Comment by xyzz** [comment]
Hello, thanks for the issue report. Can you go to the poe website and let me know if the tab contents are displayed on the inventory screen? (the one where you click your character portrait and then navigate to "stash")

**Comment by qwak-adikt** [comment]
Ah nope, looks like it has the same problem as the map tab. sorry
