### ISSUE TITLE
Is ok for new league?

### ISSUE THREAD

**Issue by alfanjorfresco** [xyzz/acquisition#540]
impossible connect to new league?

**Comment by Peter92** [comment]
Mine connects but doesn't list any characters or tabs

**Comment by master2g** [comment]
Not working for me either.... same thing as last league.  Creator probably went MIA as usual, so we'll have to wait a few days before it starts working.

**Comment by xyzz** [comment]
Does your character show on the pathofexile website? If not, then the problem (as usual) is with the API, not with the program.

**Comment by Peter92** [comment]
Working for me now, the POE website was running very slow yesterday so I probably should have realised it'd have a knock on effect haha.

**Comment by alfanjorfresco** [comment]
Yes, working for me too, enjoy the game ;)
