### ISSUE TITLE
'Type' drop down menu not visible in SSF standard

### ISSUE THREAD

**Issue by adrianjtaylor** [xyzz/acquisition#547]
Works ok in Standard. Can see all items, but can't select by type

**Comment by flesyMeM** [comment]
The types are gone for me in Standard. The only option is "Any". This is new as of patch 3.8.

**Comment by xyzz** [comment]
My understanding is that the JSON fields this feature relied on were removed from the API - see https://www.pathofexile.com/forum/view-thread/2627531

**Comment by DaneelTrevize** [comment]
Do you intend to reimplement this feature? It seems Procurement uses hardcoded substring matches to derive the category from the typeLine  
https://github.com/Stickymaddness/Procurement/blob/master/POEApi.Model/GearType/GearTypeRunner.cs

I think another, more brittle option would be to use the icon 2D Art URL.

**Comment by xyzz** [comment]
The fix is unlikely to come from me, no. If somebody contributes the feature I'll merge it of course.

**Comment by ericsium** [comment]
I just checked, actually I was already using the 2D Art URL for this feature, maybe they started quoting the slashes in the icon paths or something else must have subtly changed.  This probably isn't a difficult fix.  If you want to take this Daneel let me know, else I'll try to look at it this weekend.

**Comment by DaneelTrevize** [comment]
Ok, [I think I've got the new system done](https://github.com/DaneelTrevize/acquisition/tree/Categories_from_icon_path), I'm asking here first for a look-over before I faff with squashing it into a single change & PR.

[I also developed a new Rarity dropdown filter](https://github.com/DaneelTrevize/acquisition/tree/Filter_unidentified), and an Unidentified checkbox filter, as I find them useful in competing tools & there are outstanding raised Issues for such things here. Feedback on those would be appreciated, and whether they want to be held back for a different PR or absorbed into a single branch, or even a single change?

**Comment by ericsium** [comment]
Nice!  Looks ok to me.  I'd do two separate pull requests, one for the categorization work, the other for the filtering.

**Comment by DaneelTrevize** [comment]
Had an unexpectedly busy IRL weekend. PRs are raised, the second one being based on the first, hopefully easy to just accept both in order rather than wait for me to update my master inbetween.

**Comment by adrianjtaylor** [comment]
Hi Guys, thanks for the great work, but I don't understand how to get the modified files back into the App. Could someone give me the idiot's guide to this. I downloaded Visual Stdio etc but don't know what to do with it

**Comment by ericsium** [comment]
You need to wait for a new acquisition release which xyzz will get to when he gets to it.

**Comment by adrianjtaylor** [comment]
OK thanks for getting back to me

**Comment by DaneelTrevize** [comment]
PR #552 is also a part of this. Forgot to retest having restored the PoB export button functionality after tweaking category names.

**Comment by indeed317** [comment]
Eta on this getting pushed to public release?
