### ISSUE TITLE
Online status refreshing isn't working 

### ISSUE THREAD

**Issue by carteagle** [xyzz/acquisition#557]
I can manually refresh online status with typing https://control.poe.trade/myURL and im online, but you can' refresh every stupid 3 minutes and the Acquisition can't even do that basic thing. So sad and frustrating.

**Comment by xyzz** [comment]
Was a problem with the https redirect, should be resolved now.

**Comment by carteagle** [comment]
Yes, its working now. Really big thanks for everything!
