### ISSUE TITLE
Erro on update after windows back from hibernate / suspend

### ISSUE THREAD

**Issue by neomvll** [xyzz/acquisition#61]
Hi,
All times when windows back from hibernate or suspend mode I got this message:
WARN 2015-01-14T22:02:52.502 ItemsManagerWorker::Update called while updating

Everytime I need restart Acquisition.
Ty for the very helpfull software!!

**Comment by neomvll** [comment]
Hi dude, I again.
Well, I got the same error other times. When my connection down and back or is unstable and the acquisition keep trying get tabs. So, you can try put a time for the requisition, if this time is up, abort all requisitions and start again....I don't know, is only a idea :)
Ty dude

**Comment by xyzz** [comment]
Are there any other errors reported in the log before this one?

**Comment by neomvll** [comment]
I think yes, when happens again, I'll post here

**Comment by neomvll** [comment]
Back from suspend mode just now:
ERROR 2015-01-16T23:49:36.199 Received invalid reply instead of character list. The reply was  
ERROR 2015-01-16T23:49:36.199 The error was The document is empty. 
ERROR 2015-01-16T23:50:05.534 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. 
ERROR 2015-01-16T23:50:05.534 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. 
 WARN 2015-01-17T00:02:46.053 ItemsManagerWorker::Update called while updating 
 WARN 2015-01-17T00:04:35.492 ItemsManagerWorker::Update called while updating 

Using Win 7 updated and Acquisition updated

**Comment by xyzz** [comment]
Can you test if this installer https://xyz.is/acquisition/bin/acquisition_setup_0.1b-issue-61.exe fixes the issue for you?

**Comment by neomvll** [comment]
Sure, when need suspend time, I'll comment here

**Comment by neomvll** [comment]
After 8 hours on suspend mode, I got:
ERROR 2015-01-18T09:52:29.843 Received invalid reply instead of character list. The reply was  
ERROR 2015-01-18T09:52:29.843 The error was The document is empty. 

But now the update works fine :)
Well, I think the problem was solved.
