### ISSUE TITLE
Option to reload / autoreload only specific tabs

### ISSUE THREAD

**Issue by WhiteSp1rit** [xyzz/acquisition#64]
Option to reload / autoreload only specific tabs is an absolutely required feature - program is borderline unusable without it if a player has a large number of tabs.
There should be:
a) Option to reload one or multiple selected tabs on demand
b) Option to select which tabs are reloaded automatically. People need autoreload mostly for shops, they don't need to reload 100+ tabs every time for no reason whatsoever.

**Comment by xyzz** [comment]
Fixed by #230
