### ISSUE TITLE
Error Item not found

### ISSUE THREAD

**Issue by Destroyerx** [xyzz/acquisition#67]
everytime I move something ingame, and it starts to submit the shop to the forum, i get "error item not found"

**Comment by Destroyerx** [comment]
ERROR 2015-01-31T21:03:55.827 Error while submitting shop to forums: Failed to find item. Did you specify the correct location and x y?

**Comment by Destroyerx** [comment]
WARN 2015-01-31T21:05:53.553 23 got 'error' instead of stash tab contents

**Comment by xyzz** [comment]
that's on ggg's end, both of them; it will be fine the next refresh
