### ISSUE TITLE
Buyout age and items in buyout tabs

### ISSUE THREAD

**Issue by xyzz** [xyzz/acquisition#72]
Currently buyout age feature only works for items with single buyouts set, but I think the most way people are going to use it is put their trash items in 1a/1c/2c tabs and after a while see which items they should move a tab below. Not really sure what would be a good way to implement this though, the buyout date is set in a `Buyout` struct that's only present for items with individual buyouts.

cc @Arcane07

**Comment by Arcane07** [comment]
You're right, i forgot the tabs.
I think we have 2 possibilities.
1 - Go to 'ItemsModel::data', and put a text informing the last_update of the lab, but this will only show the tab update, not the item.

2 - Make a new SQLite column, with the json values of the item and the last_update, then when the tab is updated, we set the buyout time of all items on that tab, when a new item is 'found' in the buyout tab, we set the date and when the item changes tab too.

But i still don't know the complexity of this. What do you think ?

**Comment by xyzz** [comment]
1) that won't do
2) sqlite is only used as key-value storage (plus I didn't really understand your idea, sorry)

I was thinking about maybe reworking the system a bit. Could just assign these items a buyout, but make it a "non-sticky" buyout, which means it only works if the item's put into a tab that has the same buyout. Then we can just reuse how it works for normal buyouts. It'll probably also make shop generation more simple. But it feels like a giant hack...

**Comment by Arcane07** [comment]
No problem, that's because English is not my native language then it's sucks a little.
I think your ideia could work better. But i'll try to simplify mine.

We create a key SQLite named "item_update" or anything else, with a json format more or less like this:
```
{"ITEMHASH":{"INVENTORYID":##,"last_update":#########,},
```
Then we can check if the item changed its status (buyout change or tab with buyout change), and set the date.

**Comment by xyzz** [comment]
Branch: tabs-buyout-age.

Things left to do:
- [ ] add a way to clear item individual buyout so it respects tab-wide buyout
- [ ] tests buyout propagation
- [ ] tests for item hash migration

**Comment by EvePlayer** [comment]
Hi. That's the only feature I miss from Acquisition. GREAT application!

**Comment by xyzz** [comment]
Merged
