### ISSUE TITLE
Include tab name into item hash calculation

### ISSUE THREAD

**Issue by xyzz** [xyzz/acquisition#75]
We should start considering tab names, more precisely `item.location().GetUniqueHash()`, when calculating item hash to provide more uniqueness for it. A new `version` field is to be added to the `Buyout` struct and old buyouts are to be migrated on startup.

**Comment by Gloorf** [comment]
Also, the same bugs happens when you have unID item of the same base type (see https://www.reddit.com/r/pathofexile/comments/3katcd/anyone_else_had_this_acquisition_bug/ for proof), tab name might not be enough for every use (though it should work in 99% of the cases)

**Comment by GrappigPanda** [comment]
I have a question: this seems like a fairly simple fix. Just concatenating a tab name with the item name. Was this just forgotten and that is why it wasn't implemented? I've got no problem tackling it, but it seems like programmers who are better than me have not done it and there is probably some reason why.

Moreover, implementing this could immediately resolve a total of four issues.
xyzz/acquisition#145
xyz/acquisition#84

**Comment by xyzz** [comment]
This wasn't implemented in a separate branch but it lacks tests (need to test how well the migrations work -- wouldn't want people to lose all old buyouts), and it doesn't solve all issues. For example, it still will match exact same item if it's put to the exact same tab. There's no good solution other than GGG adding an item unique identifier to their API which is very unlikely to happen.

**Comment by xyzz** [comment]
Merged
