### ISSUE TITLE
Shop trad is more than 50000 characters long :(

### ISSUE THREAD

**Issue by AnnaZiema** [xyzz/acquisition#79]
I am selling multiple maps and quality gems.
I have one of every maps as a "display" in my b/o tab where they are accordingly priced as well. However acquisition seems to find other maps in other stash tabs and on my map dedicated chars level 1.

Is it possible to implement an option for it where it ignores completely certain stash tabs?

Thank you for your time and great programme.
A

**Comment by xyzz** [comment]
Yes it's being worked on.

**Comment by goat4dinner** [comment]
that is freaking awesome. i assume that by having more char space you would be able to avoid having multiple shop threads???

**Comment by Tvangeste** [comment]
Yes, please, an option to ignore some tabs would be great. It will help not only with the characters limit, but also with throttling when there are too many tabs to be fetched.

Here's my issue: I have 48 tabs. And Acquisition is being throttled when there are more then 45 tabs to be fetched.

Having an ability to ignore some tabs would remove the need for throttling in my case. And the UI for this is almost there already. We would just select a tab and then from the drop-down menu select something like (Exclude from updates).

Thank you!

**Comment by xyzz** [comment]
Fixed in 0.3

**Comment by RussianOfficer** [comment]
How to fix it guys? http://pix.my/R2PXJuCx - update shop throttled...
