### ISSUE TITLE
Cannot log in unsing email + pword (+ in the email)

### ISSUE THREAD

**Issue by MrTortoise** [xyzz/acquisition#86]
Hi,

Cannot login, info is defo correct. 

Worked later i think its some kind of silent lockout if you get pword wrong?
ended up using session id

**Comment by ffiarpg** [comment]
I also had this issue. I have a plus sign in my email and I was not able to login with username and password. I ended up using session id. I would recommend an update to fix this issue or at least provide a better error message.

**Comment by xyzz** [comment]
Fixed by 1599bc2daaa8d91804bbb53506dc3bbdab51a2ed

**Comment by ffiarpg** [comment]
Awesome, thanks!
