### ISSUE TITLE
Failed to find item. Did you specify the correct location and x y?

### ISSUE THREAD

**Issue by keysikg** [xyzz/acquisition#91]
I am about to give up. I have tried everything and Googled this 100 times. This is code:

"
[spoiler][linkItem location="Stash2" league="Warbands" x="10" y="0"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="4" y="0"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="11" y="0"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="9" y="0"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="9" y="2"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="10" y="2"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="10" y="8"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="11" y="5"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="0" y="11"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="0" y="0"] ~b/o 3 chaos[linkItem location="Stash2" league="Warbands" x="2" y="0"] ~b/o 3 chaos[linkItem location="Flask" character="keysikg" x="3" y="0"][linkItem location="MainInventory" character="keysikg" x="2" y="0"][linkItem location="Belt" character="keysikg" x="0" y="0"][linkItem location="MainInventory" character="keysikg" x="0" y="3"][linkItem location="Flask" character="keysikg" x="1" y="0"][linkItem location="MainInventory" character="keysikg" x="0" y="0"][linkItem location="MainInventory" character="keysikg" x="1" y="2"][linkItem location="Weapon2" character="keysikg" x="0" y="0"][linkItem location="MainInventory" character="keysikg" x="0" y="4"][linkItem location="MainInventory" character="keysikg" x="1" y="0"][linkItem location="MainInventory" character="keysikg" x="1" y="4"][linkItem location="MainInventory" character="keysikg" x="0" y="1"][linkItem location="Ring" character="keysikg" x="0" y="0"][linkItem location="Amulet" character="keysikg" x="0" y="0"][linkItem location="Weapon" character="keysikg" x="0" y="0"][linkItem location="Flask" character="keysikg" x="0" y="0"][linkItem location="BodyArmour" character="keysikg" x="0" y="0"][linkItem location="Boots" character="keysikg" x="0" y="0"][linkItem location="Gloves" character="keysikg" x="0" y="0"][linkItem location="Flask" character="keysikg" x="2" y="0"][linkItem location="Offhand2" character="keysikg" x="0" y="0"][linkItem location="Flask" character="keysikg" x="4" y="0"][linkItem location="Helm" character="keysikg" x="0" y="0"][linkItem location="Ring2" character="keysikg" x="0" y="0"][/spoiler]"

It says Failed to find item. Did you specify the correct location and x y? Every time I try to update thread(I try manually because when I hit update thread in software, it doesn't happen(probably because forum won't let you post with this error". All my items are in exact stashes as program finds them. I don't get it.

**Comment by xyzz** [comment]
Have you tried refreshing your stash?

**Comment by keysikg** [comment]
Yes, a lot of times.

**Comment by xyzz** [comment]
Okay, since it's not a lot of items I suggest you try removing them one by one until you find the item that's causing the issue, and then telling me which one was it.

**Comment by keysikg** [comment]
There are 94 items, but still, even if I could remove them 1 by 1 I wouldn't know how. Even when I ignore all these - not set prices, it simply won't post to forum. How to remove them from software to try that out?

**Comment by xyzz** [comment]
From your quote it looks like there are only 35 items. I don't mean you should ignore them in Acquisition, but rather try posting this text on forum yourself and removing [linkItem] tags one by one.

**Comment by keysikg** [comment]
I realized what was issue. My program wasn't updating code properly. So I went to Shop template and just set to [items]. Now it works. LOL. Thanks!
