### ISSUE TITLE
Failed to find item. 

### ISSUE THREAD

**Issue by daanhokse** [xyzz/acquisition#93]
So since yesterday I've been trying to make the jump from Procurement to Acquisition, but I keep getting pestered by this error:  
  
"Error while submitting shop to forums: Failed to find item. Did you specify the correct location and x y?"
  
The main window shows all my items, but the shop data/shop template is still the same as when I first loaded Acquistion.   
It's a persistent problem, I've had it continuously since yesterday, it's not solved by a refresh.

**Comment by QdbQ** [comment]
+1 same problem help pls

**Comment by xyzz** [comment]
Go to "Shop->Copy shop data to clipboard" and then paste it here.

**Comment by daanhokse** [comment]
[spoiler][linkItem location="Stash3" league="Tempest" x="0" y="1"][linkItem location="Stash3" league="Tempest" x="0" y="2"][linkItem location="Stash3" league="Tempest" x="0" y="10"][linkItem location="Stash3" league="Tempest" x="0" y="0"][linkItem location="Stash3" league="Tempest" x="0" y="9"][linkItem location="Stash3" league="Tempest" x="0" y="7"][linkItem location="Stash3" league="Tempest" x="0" y="8"][linkItem location="Stash3" league="Tempest" x="0" y="5"][linkItem location="Stash3" league="Tempest" x="0" y="4"][linkItem location="Stash9" league="Tempest" x="2" y="7"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="0" y="3"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="4" y="6"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="2" y="3"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="0" y="6"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="4" y="4"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="4" y="0"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="2" y="5"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="0" y="9"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="2" y="0"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="1" y="3"] ~b/o 2 chance[linkItem location="Stash9" league="Tempest" x="0" y="0"] ~b/o 2 chance[linkItem location="Stash8" league="Tempest" x="9" y="3"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="6" y="0"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="4" y="7"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="4" y="2"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="0" y="3"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="0" y="7"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="0" y="0"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="2" y="10"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="2" y="0"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="4" y="0"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="0" y="6"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="4" y="10"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="6" y="6"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="8" y="0"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="1" y="3"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="8" y="3"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="6" y="4"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="2" y="3"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="2" y="6"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="8" y="7"] ~b/o 2 alt[linkItem location="Stash8" league="Tempest" x="4" y="4"] ~b/o 2 alt[/spoiler]

**Comment by QdbQ** [comment]
How long will you fix this problem?

**Comment by xyzz** [comment]
Try doing what's described here: https://github.com/xyzz/acquisition/issues/91#issuecomment-120673271

**Comment by QdbQ** [comment]
[spoiler][linkItem location="Stash4" league="Standard" x="7" y="11"] ~b/o 2 exa[linkItem location="Stash4" league="Standard" x="10" y="0"] ~b/o 4 chaos[linkItem location="Stash4" league="Standard" x="9" y="11"] ~b/o 12 chaos[linkItem location="Stash4" league="Standard" x="8" y="0"] ~b/o 6 chaos[linkItem location="Stash4" league="Standard" x="11" y="0"] ~b/o 10 chaos[linkItem location="Stash4" league="Standard" x="5" y="11"] ~b/o 10 chaos[linkItem location="Stash4" league="Standard" x="10" y="11"] ~b/o 1 exa[linkItem location="Stash4" league="Standard" x="5" y="6"] ~b/o 15 alt[linkItem location="Stash4" league="Standard" x="5" y="0"] ~b/o 5 chaos[/spoiler]

    Failed to find item. Did you specify the correct location and x y?

**Comment by xyzz** [comment]
Ok, and which is the item that's causing the issue?

**Comment by QdbQ** [comment]
I put on all the tabs and objects ignored but all the same old thing copied

**Comment by QdbQ** [comment]
So what do I do?  Removing the program only helps the first time set up shop but after it copies the same thing ...

**Comment by daanhokse** [comment]
I have it solved for now by doing what the guy did in the thread you linked.  
Replacing the Shop Template back to [items], then copying shop data worked.  
In case it wasn't clear yet, the shop data doesn't update in this situation, so removing items one by one doesn't help (much). It's not a particular item that is causing the issue, it's outdated shop data.   
  
So this is a workaround that works for now, I'll keep you posted if it reoccurs.   
Are you keeping the issue open? At  least keep it open for a day or two so I can post back if it keeps happening.  

But thanks for linking the thread. I can get to selling now :P

**Comment by QdbQ** [comment]
I also work but still have problems copying and updating store

**Comment by xyzz** [comment]
I think I found the reason behind this and it should be fixed in the next build.

**Comment by daanhokse** [comment]
Thanks for looking into it!  
  
We have a workaround so frustration level is low ^_^

**Comment by xyzz** [comment]
Fixed a while ago, closing.
