### ISSUE TITLE
Error while submitting shop to forums

### ISSUE THREAD

**Issue by dzina** [xyzz/acquisition#96]
This just started today. Whenever I start Acquisiton, I get this error in the event log: "Error while submitting shop to forums: Duplicate submission token has expired. Please submit the form again. ". 

I cleared my cookies, copied session ID into the login and tried again. Now I'm getting this error: "Error while submitting shop to forums: Duplicate submission protection enabled. You may have submitted this form already. If you haven't then please submit it again. "

Any thoughts on what it could be?

**Comment by Tvangeste** [comment]
I am getting the same error messages regularly (daily) too. Have no idea what it means and what should be done to eliminate those. What form are we talking about?

**Comment by arthelinus** [comment]
same error
ERROR 2015-07-16T18:04:18.918 Error while submitting shop to forums: Duplicate submission token has expired. Please submit the form again.

**Comment by xyzz** [comment]
Does the error eventually go away? Sounds like a problem on GGG's end, or you just were browsing forums while Acquisition was updating your shop and the token has expired.

**Comment by Tvangeste** [comment]
I usually restart the Acquisition a couple of times for the error to disappear (usually until the next day).

**Comment by Tvangeste** [comment]
I couldn't make the error go away today. And I have no idea whether it blocks the shop updates or not. But it is getting really, really, really annoying, to deal with this every day :)

Could something be done here? What is the reason for the error, what does it mean even?

**Comment by xyzz** [comment]
No reply for over a month.
