### ISSUE TITLE
Acquisition 0.2f installer blocked by Windows Smartscreen

### ISSUE THREAD

**Issue by HeavensRejected** [xyzz/acquisition#97]
I've just downloaded the installer and when I try to start it gets blocked by Windows Smartscreen.

I'm pretty sure the download is clean, you might want to look into it why Windows thinks it's bad as some people probably won't know their way around Windows enough to turn it off.

**Comment by xyzz** [comment]
what windows version is that?

**Comment by HeavensRejected** [comment]
Windows 8.1

**Comment by xyzz** [comment]
Okay, thanks, I'll see what I can do about that.

**Comment by HeavensRejected** [comment]
Thanks! Keep up the good work :)

**Comment by xyzz** [comment]
Nothing we can do about it without paying $$$ for the certificate, the warning eventually goes away.
