### ISSUE TITLE
"No Price" on whole tab doesn't apply to all items

### ISSUE THREAD

**Issue by foreAndaway** [xyzz/acquisition#99]
I have to manually select No price for each item, else everything in the tab is ignored

**Comment by xyzz** [comment]
Items' buyouts override tab buyout they are in, this is by design.

**Comment by xyzz** [comment]
I've tried multiple times and it seems to work fine, do you have more information on how to reproduce this?

**Comment by ericsium** [comment]
The mechanism was changed a lot with #267 so closing this.
